// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: bridge.proto

package dmcnpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BridgeTrustTier represents the trust classification assigned to an
// inbound legacy email message by the bridge node.
// See whitepaper Section 15.6.2.
type BridgeTrustTier int32

const (
	BridgeTrustTier_BRIDGE_TRUST_TIER_UNSPECIFIED       BridgeTrustTier = 0
	BridgeTrustTier_BRIDGE_TRUST_TIER_VERIFIED_LEGACY   BridgeTrustTier = 1
	BridgeTrustTier_BRIDGE_TRUST_TIER_UNVERIFIED_LEGACY BridgeTrustTier = 2
	BridgeTrustTier_BRIDGE_TRUST_TIER_SUSPICIOUS        BridgeTrustTier = 3
)

// Enum value maps for BridgeTrustTier.
var (
	BridgeTrustTier_name = map[int32]string{
		0: "BRIDGE_TRUST_TIER_UNSPECIFIED",
		1: "BRIDGE_TRUST_TIER_VERIFIED_LEGACY",
		2: "BRIDGE_TRUST_TIER_UNVERIFIED_LEGACY",
		3: "BRIDGE_TRUST_TIER_SUSPICIOUS",
	}
	BridgeTrustTier_value = map[string]int32{
		"BRIDGE_TRUST_TIER_UNSPECIFIED":       0,
		"BRIDGE_TRUST_TIER_VERIFIED_LEGACY":   1,
		"BRIDGE_TRUST_TIER_UNVERIFIED_LEGACY": 2,
		"BRIDGE_TRUST_TIER_SUSPICIOUS":        3,
	}
)

func (x BridgeTrustTier) Enum() *BridgeTrustTier {
	p := new(BridgeTrustTier)
	*p = x
	return p
}

func (x BridgeTrustTier) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BridgeTrustTier) Descriptor() protoreflect.EnumDescriptor {
	return file_bridge_proto_enumTypes[0].Descriptor()
}

func (BridgeTrustTier) Type() protoreflect.EnumType {
	return &file_bridge_proto_enumTypes[0]
}

func (x BridgeTrustTier) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BridgeTrustTier.Descriptor instead.
func (BridgeTrustTier) EnumDescriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{0}
}

// SPFResult represents the outcome of an SPF check on inbound email.
type SPFResult int32

const (
	SPFResult_SPF_RESULT_UNSPECIFIED SPFResult = 0
	SPFResult_SPF_RESULT_PASS        SPFResult = 1
	SPFResult_SPF_RESULT_FAIL        SPFResult = 2
	SPFResult_SPF_RESULT_SOFTFAIL    SPFResult = 3
	SPFResult_SPF_RESULT_NEUTRAL     SPFResult = 4
)

// Enum value maps for SPFResult.
var (
	SPFResult_name = map[int32]string{
		0: "SPF_RESULT_UNSPECIFIED",
		1: "SPF_RESULT_PASS",
		2: "SPF_RESULT_FAIL",
		3: "SPF_RESULT_SOFTFAIL",
		4: "SPF_RESULT_NEUTRAL",
	}
	SPFResult_value = map[string]int32{
		"SPF_RESULT_UNSPECIFIED": 0,
		"SPF_RESULT_PASS":        1,
		"SPF_RESULT_FAIL":        2,
		"SPF_RESULT_SOFTFAIL":    3,
		"SPF_RESULT_NEUTRAL":     4,
	}
)

func (x SPFResult) Enum() *SPFResult {
	p := new(SPFResult)
	*p = x
	return p
}

func (x SPFResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SPFResult) Descriptor() protoreflect.EnumDescriptor {
	return file_bridge_proto_enumTypes[1].Descriptor()
}

func (SPFResult) Type() protoreflect.EnumType {
	return &file_bridge_proto_enumTypes[1]
}

func (x SPFResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SPFResult.Descriptor instead.
func (SPFResult) EnumDescriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{1}
}

// DKIMResult represents the outcome of a DKIM check on inbound email.
type DKIMResult int32

const (
	DKIMResult_DKIM_RESULT_UNSPECIFIED DKIMResult = 0
	DKIMResult_DKIM_RESULT_PASS        DKIMResult = 1
	DKIMResult_DKIM_RESULT_FAIL        DKIMResult = 2
)

// Enum value maps for DKIMResult.
var (
	DKIMResult_name = map[int32]string{
		0: "DKIM_RESULT_UNSPECIFIED",
		1: "DKIM_RESULT_PASS",
		2: "DKIM_RESULT_FAIL",
	}
	DKIMResult_value = map[string]int32{
		"DKIM_RESULT_UNSPECIFIED": 0,
		"DKIM_RESULT_PASS":        1,
		"DKIM_RESULT_FAIL":        2,
	}
)

func (x DKIMResult) Enum() *DKIMResult {
	p := new(DKIMResult)
	*p = x
	return p
}

func (x DKIMResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DKIMResult) Descriptor() protoreflect.EnumDescriptor {
	return file_bridge_proto_enumTypes[2].Descriptor()
}

func (DKIMResult) Type() protoreflect.EnumType {
	return &file_bridge_proto_enumTypes[2]
}

func (x DKIMResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DKIMResult.Descriptor instead.
func (DKIMResult) EnumDescriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{2}
}

// DMARCResult represents the outcome of a DMARC check on inbound email.
type DMARCResult int32

const (
	DMARCResult_DMARC_RESULT_UNSPECIFIED DMARCResult = 0
	DMARCResult_DMARC_RESULT_PASS        DMARCResult = 1
	DMARCResult_DMARC_RESULT_FAIL        DMARCResult = 2
)

// Enum value maps for DMARCResult.
var (
	DMARCResult_name = map[int32]string{
		0: "DMARC_RESULT_UNSPECIFIED",
		1: "DMARC_RESULT_PASS",
		2: "DMARC_RESULT_FAIL",
	}
	DMARCResult_value = map[string]int32{
		"DMARC_RESULT_UNSPECIFIED": 0,
		"DMARC_RESULT_PASS":        1,
		"DMARC_RESULT_FAIL":        2,
	}
)

func (x DMARCResult) Enum() *DMARCResult {
	p := new(DMARCResult)
	*p = x
	return p
}

func (x DMARCResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DMARCResult) Descriptor() protoreflect.EnumDescriptor {
	return file_bridge_proto_enumTypes[3].Descriptor()
}

func (DMARCResult) Type() protoreflect.EnumType {
	return &file_bridge_proto_enumTypes[3]
}

func (x DMARCResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DMARCResult.Descriptor instead.
func (DMARCResult) EnumDescriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{3}
}

// BridgeClassificationRecord is a signed attestation by a bridge node
// describing the authentication outcome of an inbound legacy email.
// See whitepaper Section 15.6.2.
type BridgeClassificationRecord struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BridgeAddress   string                 `protobuf:"bytes,1,opt,name=bridge_address,json=bridgeAddress,proto3" json:"bridge_address,omitempty"`         // DMCN address of the bridge operator
	BridgePublicKey []byte                 `protobuf:"bytes,2,opt,name=bridge_public_key,json=bridgePublicKey,proto3" json:"bridge_public_key,omitempty"` // 32 bytes Ed25519 public key
	SmtpFrom        string                 `protobuf:"bytes,3,opt,name=smtp_from,json=smtpFrom,proto3" json:"smtp_from,omitempty"`                        // original SMTP From address
	SmtpSenderIp    string                 `protobuf:"bytes,4,opt,name=smtp_sender_ip,json=smtpSenderIp,proto3" json:"smtp_sender_ip,omitempty"`          // sending server IP address
	SpfResult       SPFResult              `protobuf:"varint,5,opt,name=spf_result,json=spfResult,proto3,enum=dmcn.bridge.SPFResult" json:"spf_result,omitempty"`
	DkimResult      DKIMResult             `protobuf:"varint,6,opt,name=dkim_result,json=dkimResult,proto3,enum=dmcn.bridge.DKIMResult" json:"dkim_result,omitempty"`
	DmarcResult     DMARCResult            `protobuf:"varint,7,opt,name=dmarc_result,json=dmarcResult,proto3,enum=dmcn.bridge.DMARCResult" json:"dmarc_result,omitempty"`
	ReputationScore int32                  `protobuf:"varint,8,opt,name=reputation_score,json=reputationScore,proto3" json:"reputation_score,omitempty"` // -100 to +100; 0 = neutral
	TrustTier       BridgeTrustTier        `protobuf:"varint,9,opt,name=trust_tier,json=trustTier,proto3,enum=dmcn.bridge.BridgeTrustTier" json:"trust_tier,omitempty"`
	ClassifiedAt    int64                  `protobuf:"varint,10,opt,name=classified_at,json=classifiedAt,proto3" json:"classified_at,omitempty"`         // Unix seconds
	BridgeSignature []byte                 `protobuf:"bytes,11,opt,name=bridge_signature,json=bridgeSignature,proto3" json:"bridge_signature,omitempty"` // 64 bytes Ed25519 sig over all preceding fields
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BridgeClassificationRecord) Reset() {
	*x = BridgeClassificationRecord{}
	mi := &file_bridge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BridgeClassificationRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BridgeClassificationRecord) ProtoMessage() {}

func (x *BridgeClassificationRecord) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BridgeClassificationRecord.ProtoReflect.Descriptor instead.
func (*BridgeClassificationRecord) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{0}
}

func (x *BridgeClassificationRecord) GetBridgeAddress() string {
	if x != nil {
		return x.BridgeAddress
	}
	return ""
}

func (x *BridgeClassificationRecord) GetBridgePublicKey() []byte {
	if x != nil {
		return x.BridgePublicKey
	}
	return nil
}

func (x *BridgeClassificationRecord) GetSmtpFrom() string {
	if x != nil {
		return x.SmtpFrom
	}
	return ""
}

func (x *BridgeClassificationRecord) GetSmtpSenderIp() string {
	if x != nil {
		return x.SmtpSenderIp
	}
	return ""
}

func (x *BridgeClassificationRecord) GetSpfResult() SPFResult {
	if x != nil {
		return x.SpfResult
	}
	return SPFResult_SPF_RESULT_UNSPECIFIED
}

func (x *BridgeClassificationRecord) GetDkimResult() DKIMResult {
	if x != nil {
		return x.DkimResult
	}
	return DKIMResult_DKIM_RESULT_UNSPECIFIED
}

func (x *BridgeClassificationRecord) GetDmarcResult() DMARCResult {
	if x != nil {
		return x.DmarcResult
	}
	return DMARCResult_DMARC_RESULT_UNSPECIFIED
}

func (x *BridgeClassificationRecord) GetReputationScore() int32 {
	if x != nil {
		return x.ReputationScore
	}
	return 0
}

func (x *BridgeClassificationRecord) GetTrustTier() BridgeTrustTier {
	if x != nil {
		return x.TrustTier
	}
	return BridgeTrustTier_BRIDGE_TRUST_TIER_UNSPECIFIED
}

func (x *BridgeClassificationRecord) GetClassifiedAt() int64 {
	if x != nil {
		return x.ClassifiedAt
	}
	return 0
}

func (x *BridgeClassificationRecord) GetBridgeSignature() []byte {
	if x != nil {
		return x.BridgeSignature
	}
	return nil
}

// BridgeDeliveryReceipt is a signed receipt from the bridge confirming
// outbound SMTP delivery of a DMCN message.
type BridgeDeliveryReceipt struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OriginalMessageId []byte                 `protobuf:"bytes,1,opt,name=original_message_id,json=originalMessageId,proto3" json:"original_message_id,omitempty"` // 16 bytes UUID of the original message
	RecipientEmail    string                 `protobuf:"bytes,2,opt,name=recipient_email,json=recipientEmail,proto3" json:"recipient_email,omitempty"`            // legacy email address delivered to
	BridgeAddress     string                 `protobuf:"bytes,3,opt,name=bridge_address,json=bridgeAddress,proto3" json:"bridge_address,omitempty"`               // DMCN address of the bridge operator
	DeliveredAt       int64                  `protobuf:"varint,4,opt,name=delivered_at,json=deliveredAt,proto3" json:"delivered_at,omitempty"`                    // Unix seconds
	Success           bool                   `protobuf:"varint,5,opt,name=success,proto3" json:"success,omitempty"`
	ErrorDetail       string                 `protobuf:"bytes,6,opt,name=error_detail,json=errorDetail,proto3" json:"error_detail,omitempty"`             // empty on success
	BridgeSignature   []byte                 `protobuf:"bytes,7,opt,name=bridge_signature,json=bridgeSignature,proto3" json:"bridge_signature,omitempty"` // 64 bytes Ed25519 sig over all preceding fields
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *BridgeDeliveryReceipt) Reset() {
	*x = BridgeDeliveryReceipt{}
	mi := &file_bridge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BridgeDeliveryReceipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BridgeDeliveryReceipt) ProtoMessage() {}

func (x *BridgeDeliveryReceipt) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BridgeDeliveryReceipt.ProtoReflect.Descriptor instead.
func (*BridgeDeliveryReceipt) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{1}
}

func (x *BridgeDeliveryReceipt) GetOriginalMessageId() []byte {
	if x != nil {
		return x.OriginalMessageId
	}
	return nil
}

func (x *BridgeDeliveryReceipt) GetRecipientEmail() string {
	if x != nil {
		return x.RecipientEmail
	}
	return ""
}

func (x *BridgeDeliveryReceipt) GetBridgeAddress() string {
	if x != nil {
		return x.BridgeAddress
	}
	return ""
}

func (x *BridgeDeliveryReceipt) GetDeliveredAt() int64 {
	if x != nil {
		return x.DeliveredAt
	}
	return 0
}

func (x *BridgeDeliveryReceipt) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BridgeDeliveryReceipt) GetErrorDetail() string {
	if x != nil {
		return x.ErrorDetail
	}
	return ""
}

func (x *BridgeDeliveryReceipt) GetBridgeSignature() []byte {
	if x != nil {
		return x.BridgeSignature
	}
	return nil
}

var File_bridge_proto protoreflect.FileDescriptor

const file_bridge_proto_rawDesc = "" +
	"\n" +
	"\fbridge.proto\x12\vdmcn.bridge\"\x98\x04\n" +
	"\x1aBridgeClassificationRecord\x12%\n" +
	"\x0ebridge_address\x18\x01 \x01(\tR\rbridgeAddress\x12*\n" +
	"\x11bridge_public_key\x18\x02 \x01(\fR\x0fbridgePublicKey\x12\x1b\n" +
	"\tsmtp_from\x18\x03 \x01(\tR\bsmtpFrom\x12$\n" +
	"\x0esmtp_sender_ip\x18\x04 \x01(\tR\fsmtpSenderIp\x125\n" +
	"\n" +
	"spf_result\x18\x05 \x01(\x0e2\x16.dmcn.bridge.SPFResultR\tspfResult\x128\n" +
	"\vdkim_result\x18\x06 \x01(\x0e2\x17.dmcn.bridge.DKIMResultR\n" +
	"dkimResult\x12;\n" +
	"\fdmarc_result\x18\a \x01(\x0e2\x18.dmcn.bridge.DMARCResultR\vdmarcResult\x12)\n" +
	"\x10reputation_score\x18\b \x01(\x05R\x0freputationScore\x12;\n" +
	"\n" +
	"trust_tier\x18\t \x01(\x0e2\x1c.dmcn.bridge.BridgeTrustTierR\ttrustTier\x12#\n" +
	"\rclassified_at\x18\n" +
	" \x01(\x03R\fclassifiedAt\x12)\n" +
	"\x10bridge_signature\x18\v \x01(\fR\x0fbridgeSignature\"\xa2\x02\n" +
	"\x15BridgeDeliveryReceipt\x12.\n" +
	"\x13original_message_id\x18\x01 \x01(\fR\x11originalMessageId\x12'\n" +
	"\x0frecipient_email\x18\x02 \x01(\tR\x0erecipientEmail\x12%\n" +
	"\x0ebridge_address\x18\x03 \x01(\tR\rbridgeAddress\x12!\n" +
	"\fdelivered_at\x18\x04 \x01(\x03R\vdeliveredAt\x12\x18\n" +
	"\asuccess\x18\x05 \x01(\bR\asuccess\x12!\n" +
	"\ferror_detail\x18\x06 \x01(\tR\verrorDetail\x12)\n" +
	"\x10bridge_signature\x18\a \x01(\fR\x0fbridgeSignature*\xa6\x01\n" +
	"\x0fBridgeTrustTier\x12!\n" +
	"\x1dBRIDGE_TRUST_TIER_UNSPECIFIED\x10\x00\x12%\n" +
	"!BRIDGE_TRUST_TIER_VERIFIED_LEGACY\x10\x01\x12'\n" +
	"#BRIDGE_TRUST_TIER_UNVERIFIED_LEGACY\x10\x02\x12 \n" +
	"\x1cBRIDGE_TRUST_TIER_SUSPICIOUS\x10\x03*\x82\x01\n" +
	"\tSPFResult\x12\x1a\n" +
	"\x16SPF_RESULT_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fSPF_RESULT_PASS\x10\x01\x12\x13\n" +
	"\x0fSPF_RESULT_FAIL\x10\x02\x12\x17\n" +
	"\x13SPF_RESULT_SOFTFAIL\x10\x03\x12\x16\n" +
	"\x12SPF_RESULT_NEUTRAL\x10\x04*U\n" +
	"\n" +
	"DKIMResult\x12\x1b\n" +
	"\x17DKIM_RESULT_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10DKIM_RESULT_PASS\x10\x01\x12\x14\n" +
	"\x10DKIM_RESULT_FAIL\x10\x02*Y\n" +
	"\vDMARCResult\x12\x1c\n" +
	"\x18DMARC_RESULT_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11DMARC_RESULT_PASS\x10\x01\x12\x15\n" +
	"\x11DMARC_RESULT_FAIL\x10\x02B-Z+github.com/mertenvg/open-dmcn/dmcnpb;dmcnpbb\x06proto3"

var (
	file_bridge_proto_rawDescOnce sync.Once
	file_bridge_proto_rawDescData []byte
)

func file_bridge_proto_rawDescGZIP() []byte {
	file_bridge_proto_rawDescOnce.Do(func() {
		file_bridge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bridge_proto_rawDesc), len(file_bridge_proto_rawDesc)))
	})
	return file_bridge_proto_rawDescData
}

var file_bridge_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_bridge_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_bridge_proto_goTypes = []any{
	(BridgeTrustTier)(0),               // 0: dmcn.bridge.BridgeTrustTier
	(SPFResult)(0),                     // 1: dmcn.bridge.SPFResult
	(DKIMResult)(0),                    // 2: dmcn.bridge.DKIMResult
	(DMARCResult)(0),                   // 3: dmcn.bridge.DMARCResult
	(*BridgeClassificationRecord)(nil), // 4: dmcn.bridge.BridgeClassificationRecord
	(*BridgeDeliveryReceipt)(nil),      // 5: dmcn.bridge.BridgeDeliveryReceipt
}
var file_bridge_proto_depIdxs = []int32{
	1, // 0: dmcn.bridge.BridgeClassificationRecord.spf_result:type_name -> dmcn.bridge.SPFResult
	2, // 1: dmcn.bridge.BridgeClassificationRecord.dkim_result:type_name -> dmcn.bridge.DKIMResult
	3, // 2: dmcn.bridge.BridgeClassificationRecord.dmarc_result:type_name -> dmcn.bridge.DMARCResult
	0, // 3: dmcn.bridge.BridgeClassificationRecord.trust_tier:type_name -> dmcn.bridge.BridgeTrustTier
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_bridge_proto_init() }
func file_bridge_proto_init() {
	if File_bridge_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bridge_proto_rawDesc), len(file_bridge_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bridge_proto_goTypes,
		DependencyIndexes: file_bridge_proto_depIdxs,
		EnumInfos:         file_bridge_proto_enumTypes,
		MessageInfos:      file_bridge_proto_msgTypes,
	}.Build()
	File_bridge_proto = out.File
	file_bridge_proto_goTypes = nil
	file_bridge_proto_depIdxs = nil
}
