// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: identity.proto

package dmcnpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// VerificationTier represents the level of identity verification.
// See whitepaper Section 15.2.2.
// Only DOMAIN_DNS and DANE are valid for registered addresses; provider-hosted
// address claiming is not supported (see Section 12 for rationale).
type VerificationTier int32

const (
	VerificationTier_VERIFICATION_TIER_UNVERIFIED VerificationTier = 0
	VerificationTier_VERIFICATION_TIER_DOMAIN_DNS VerificationTier = 2
	VerificationTier_VERIFICATION_TIER_DANE       VerificationTier = 3
)

// Enum value maps for VerificationTier.
var (
	VerificationTier_name = map[int32]string{
		0: "VERIFICATION_TIER_UNVERIFIED",
		2: "VERIFICATION_TIER_DOMAIN_DNS",
		3: "VERIFICATION_TIER_DANE",
	}
	VerificationTier_value = map[string]int32{
		"VERIFICATION_TIER_UNVERIFIED": 0,
		"VERIFICATION_TIER_DOMAIN_DNS": 2,
		"VERIFICATION_TIER_DANE":       3,
	}
)

func (x VerificationTier) Enum() *VerificationTier {
	p := new(VerificationTier)
	*p = x
	return p
}

func (x VerificationTier) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VerificationTier) Descriptor() protoreflect.EnumDescriptor {
	return file_identity_proto_enumTypes[0].Descriptor()
}

func (VerificationTier) Type() protoreflect.EnumType {
	return &file_identity_proto_enumTypes[0]
}

func (x VerificationTier) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VerificationTier.Descriptor instead.
func (VerificationTier) EnumDescriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{0}
}

// AttestationType represents the method of attestation.
// See whitepaper Section 15.2.3.
type AttestationType int32

const (
	AttestationType_ATTESTATION_TYPE_UNSPECIFIED    AttestationType = 0
	AttestationType_ATTESTATION_TYPE_IN_PERSON      AttestationType = 1
	AttestationType_ATTESTATION_TYPE_FINGERPRINT    AttestationType = 2
	AttestationType_ATTESTATION_TYPE_NETWORK        AttestationType = 3
	AttestationType_ATTESTATION_TYPE_ORGANISATIONAL AttestationType = 4
)

// Enum value maps for AttestationType.
var (
	AttestationType_name = map[int32]string{
		0: "ATTESTATION_TYPE_UNSPECIFIED",
		1: "ATTESTATION_TYPE_IN_PERSON",
		2: "ATTESTATION_TYPE_FINGERPRINT",
		3: "ATTESTATION_TYPE_NETWORK",
		4: "ATTESTATION_TYPE_ORGANISATIONAL",
	}
	AttestationType_value = map[string]int32{
		"ATTESTATION_TYPE_UNSPECIFIED":    0,
		"ATTESTATION_TYPE_IN_PERSON":      1,
		"ATTESTATION_TYPE_FINGERPRINT":    2,
		"ATTESTATION_TYPE_NETWORK":        3,
		"ATTESTATION_TYPE_ORGANISATIONAL": 4,
	}
)

func (x AttestationType) Enum() *AttestationType {
	p := new(AttestationType)
	*p = x
	return p
}

func (x AttestationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AttestationType) Descriptor() protoreflect.EnumDescriptor {
	return file_identity_proto_enumTypes[1].Descriptor()
}

func (AttestationType) Type() protoreflect.EnumType {
	return &file_identity_proto_enumTypes[1]
}

func (x AttestationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AttestationType.Descriptor instead.
func (AttestationType) EnumDescriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{1}
}

// AttestationRecord represents a web-of-trust attestation.
// See whitepaper Section 15.2.3.
type AttestationRecord struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AttesterAddress string                 `protobuf:"bytes,1,opt,name=attester_address,json=attesterAddress,proto3" json:"attester_address,omitempty"`
	AttesterPubkey  []byte                 `protobuf:"bytes,2,opt,name=attester_pubkey,json=attesterPubkey,proto3" json:"attester_pubkey,omitempty"` // 32 bytes Ed25519
	SubjectAddress  string                 `protobuf:"bytes,3,opt,name=subject_address,json=subjectAddress,proto3" json:"subject_address,omitempty"`
	SubjectPubkey   []byte                 `protobuf:"bytes,4,opt,name=subject_pubkey,json=subjectPubkey,proto3" json:"subject_pubkey,omitempty"` // 32 bytes Ed25519
	AttestationType AttestationType        `protobuf:"varint,5,opt,name=attestation_type,json=attestationType,proto3,enum=dmcn.identity.AttestationType" json:"attestation_type,omitempty"`
	AttestedAt      int64                  `protobuf:"varint,6,opt,name=attested_at,json=attestedAt,proto3" json:"attested_at,omitempty"` // Unix seconds
	ExpiresAt       int64                  `protobuf:"varint,7,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`    // Unix seconds; 0 = no expiry
	Signature       []byte                 `protobuf:"bytes,8,opt,name=signature,proto3" json:"signature,omitempty"`                      // 64 bytes Ed25519 sig over all preceding fields
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AttestationRecord) Reset() {
	*x = AttestationRecord{}
	mi := &file_identity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttestationRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttestationRecord) ProtoMessage() {}

func (x *AttestationRecord) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttestationRecord.ProtoReflect.Descriptor instead.
func (*AttestationRecord) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{0}
}

func (x *AttestationRecord) GetAttesterAddress() string {
	if x != nil {
		return x.AttesterAddress
	}
	return ""
}

func (x *AttestationRecord) GetAttesterPubkey() []byte {
	if x != nil {
		return x.AttesterPubkey
	}
	return nil
}

func (x *AttestationRecord) GetSubjectAddress() string {
	if x != nil {
		return x.SubjectAddress
	}
	return ""
}

func (x *AttestationRecord) GetSubjectPubkey() []byte {
	if x != nil {
		return x.SubjectPubkey
	}
	return nil
}

func (x *AttestationRecord) GetAttestationType() AttestationType {
	if x != nil {
		return x.AttestationType
	}
	return AttestationType_ATTESTATION_TYPE_UNSPECIFIED
}

func (x *AttestationRecord) GetAttestedAt() int64 {
	if x != nil {
		return x.AttestedAt
	}
	return 0
}

func (x *AttestationRecord) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *AttestationRecord) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// IdentityRecord is a self-certifying identity binding.
// See whitepaper Section 15.2.2.
type IdentityRecord struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Version          uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Address          string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`                                             // local@domain
	Ed25519PublicKey []byte                 `protobuf:"bytes,3,opt,name=ed25519_public_key,json=ed25519PublicKey,proto3" json:"ed25519_public_key,omitempty"` // 32 bytes
	X25519PublicKey  []byte                 `protobuf:"bytes,4,opt,name=x25519_public_key,json=x25519PublicKey,proto3" json:"x25519_public_key,omitempty"`    // 32 bytes
	CreatedAt        int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                       // Unix seconds
	ExpiresAt        int64                  `protobuf:"varint,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`                       // Unix seconds; 0 = no expiry
	RelayHints       []string               `protobuf:"bytes,7,rep,name=relay_hints,json=relayHints,proto3" json:"relay_hints,omitempty"`
	VerificationTier VerificationTier       `protobuf:"varint,8,opt,name=verification_tier,json=verificationTier,proto3,enum=dmcn.identity.VerificationTier" json:"verification_tier,omitempty"`
	Attestations     []*AttestationRecord   `protobuf:"bytes,9,rep,name=attestations,proto3" json:"attestations,omitempty"`
	SelfSignature    []byte                 `protobuf:"bytes,10,opt,name=self_signature,json=selfSignature,proto3" json:"self_signature,omitempty"` // 64 bytes Ed25519 sig over all preceding fields
	// Bridge capability flag — true if this identity operates as a bridge node.
	// See whitepaper Section 15.6.
	BridgeCapability bool `protobuf:"varint,19,opt,name=bridge_capability,json=bridgeCapability,proto3" json:"bridge_capability,omitempty"`
	// Domain Authority countersignature (whitepaper Section 13.2). Present when a
	// domain authority — directly, or via a delegated sub-authority — vouches for
	// this address↔keys binding. Excluded from the self-signature: the authority
	// signs after the user self-signs.
	DomainCountersignature    []byte `protobuf:"bytes,20,opt,name=domain_countersignature,json=domainCountersignature,proto3" json:"domain_countersignature,omitempty"`            // 64 bytes Ed25519 over the binding
	DomainCountersignedAt     int64  `protobuf:"varint,21,opt,name=domain_countersigned_at,json=domainCountersignedAt,proto3" json:"domain_countersigned_at,omitempty"`            // Unix seconds; authenticated time of countersigning
	DomainCountersignerPubkey []byte `protobuf:"bytes,22,opt,name=domain_countersigner_pubkey,json=domainCountersignerPubkey,proto3" json:"domain_countersigner_pubkey,omitempty"` // 32 bytes Ed25519 of the root or sub-authority signer
	// require_onion: the mailbox owner requires inbound mail to arrive via onion
	// routing (senders use onion; the recipient's relay rejects direct STOREs).
	// Covered by the self-signature. See whitepaper Section 15.4.
	RequireOnion bool `protobuf:"varint,23,opt,name=require_onion,json=requireOnion,proto3" json:"require_onion,omitempty"`
	// address_credential (Credential PKI): the domain's attestation of this address↔key
	// binding (role "address"), replacing the domain_countersignature fields. The user
	// self-signature above still binds the keys; the credential is the domain's
	// signature, issued AFTER (so excluded from the self-signature). Preferred over the
	// legacy countersignature when present.
	AddressCredential *Credential `protobuf:"bytes,24,opt,name=address_credential,json=addressCredential,proto3" json:"address_credential,omitempty"`
	// routing_credential (Credential PKI): the OPERATOR's attestation of this address's
	// mailbox routing (role "routing", carrying the authoritative relay_hints). RelayHints
	// is operational, not identity — it is OWNED BY THE OPERATOR, excluded from the owner
	// self-signature (field 7 above is a reader-facing mirror), and signed here by the
	// domain authority/sub-authority. This lets an operator re-point/rebalance routing
	// without the mailbox owner's key. The credential's relay_hints are authoritative.
	RoutingCredential *Credential `protobuf:"bytes,25,opt,name=routing_credential,json=routingCredential,proto3" json:"routing_credential,omitempty"`
	// revision is the owner-signed monotonic version of the identity core, bumped on every
	// owner re-sign (key rotation, expiry refresh). Covered by the self-signature, so only the
	// owner can advance it. Fleet PutRecord + the resolver use it for anti-rollback: a record
	// with a lower revision cannot overwrite a higher one (routing-credential-only updates,
	// which don't touch the owner core, tiebreak on the routing credential's issued_at).
	Revision uint64 `protobuf:"varint,26,opt,name=revision,proto3" json:"revision,omitempty"`
	// operator_credentials: OPERATOR-attached credentials beyond routing — the generic
	// extension point for operator-owned, per-account attestations (semantics identified by
	// each credential's roles/attributes). Excluded from the owner self-signature exactly like
	// fields 24/25: issued and re-issued without the owner's key. Same-revision anti-rollback
	// tiebreak: the newest issued_at across routing_credential AND operator_credentials wins.
	OperatorCredentials []*Credential `protobuf:"bytes,28,rep,name=operator_credentials,json=operatorCredentials,proto3" json:"operator_credentials,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *IdentityRecord) Reset() {
	*x = IdentityRecord{}
	mi := &file_identity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityRecord) ProtoMessage() {}

func (x *IdentityRecord) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityRecord.ProtoReflect.Descriptor instead.
func (*IdentityRecord) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{1}
}

func (x *IdentityRecord) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *IdentityRecord) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *IdentityRecord) GetEd25519PublicKey() []byte {
	if x != nil {
		return x.Ed25519PublicKey
	}
	return nil
}

func (x *IdentityRecord) GetX25519PublicKey() []byte {
	if x != nil {
		return x.X25519PublicKey
	}
	return nil
}

func (x *IdentityRecord) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *IdentityRecord) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *IdentityRecord) GetRelayHints() []string {
	if x != nil {
		return x.RelayHints
	}
	return nil
}

func (x *IdentityRecord) GetVerificationTier() VerificationTier {
	if x != nil {
		return x.VerificationTier
	}
	return VerificationTier_VERIFICATION_TIER_UNVERIFIED
}

func (x *IdentityRecord) GetAttestations() []*AttestationRecord {
	if x != nil {
		return x.Attestations
	}
	return nil
}

func (x *IdentityRecord) GetSelfSignature() []byte {
	if x != nil {
		return x.SelfSignature
	}
	return nil
}

func (x *IdentityRecord) GetBridgeCapability() bool {
	if x != nil {
		return x.BridgeCapability
	}
	return false
}

func (x *IdentityRecord) GetDomainCountersignature() []byte {
	if x != nil {
		return x.DomainCountersignature
	}
	return nil
}

func (x *IdentityRecord) GetDomainCountersignedAt() int64 {
	if x != nil {
		return x.DomainCountersignedAt
	}
	return 0
}

func (x *IdentityRecord) GetDomainCountersignerPubkey() []byte {
	if x != nil {
		return x.DomainCountersignerPubkey
	}
	return nil
}

func (x *IdentityRecord) GetRequireOnion() bool {
	if x != nil {
		return x.RequireOnion
	}
	return false
}

func (x *IdentityRecord) GetAddressCredential() *Credential {
	if x != nil {
		return x.AddressCredential
	}
	return nil
}

func (x *IdentityRecord) GetRoutingCredential() *Credential {
	if x != nil {
		return x.RoutingCredential
	}
	return nil
}

func (x *IdentityRecord) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *IdentityRecord) GetOperatorCredentials() []*Credential {
	if x != nil {
		return x.OperatorCredentials
	}
	return nil
}

// AuthorityKey is one entry in a domain root authority's key timeline.
// effective_from-only: a key is effective from effective_from until the next
// key's effective_from; the latest key is open-ended (whitepaper Section 13.1).
type AuthorityKey struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Ed25519PublicKey []byte                 `protobuf:"bytes,1,opt,name=ed25519_public_key,json=ed25519PublicKey,proto3" json:"ed25519_public_key,omitempty"` // 32 bytes
	X25519PublicKey  []byte                 `protobuf:"bytes,2,opt,name=x25519_public_key,json=x25519PublicKey,proto3" json:"x25519_public_key,omitempty"`    // 32 bytes
	EffectiveFrom    int64                  `protobuf:"varint,3,opt,name=effective_from,json=effectiveFrom,proto3" json:"effective_from,omitempty"`           // Unix seconds
	RotationReason   uint32                 `protobuf:"varint,4,opt,name=rotation_reason,json=rotationReason,proto3" json:"rotation_reason,omitempty"`        // carried-unenforced; for the future revocation phase
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AuthorityKey) Reset() {
	*x = AuthorityKey{}
	mi := &file_identity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorityKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorityKey) ProtoMessage() {}

func (x *AuthorityKey) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorityKey.ProtoReflect.Descriptor instead.
func (*AuthorityKey) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{2}
}

func (x *AuthorityKey) GetEd25519PublicKey() []byte {
	if x != nil {
		return x.Ed25519PublicKey
	}
	return nil
}

func (x *AuthorityKey) GetX25519PublicKey() []byte {
	if x != nil {
		return x.X25519PublicKey
	}
	return nil
}

func (x *AuthorityKey) GetEffectiveFrom() int64 {
	if x != nil {
		return x.EffectiveFrom
	}
	return 0
}

func (x *AuthorityKey) GetRotationReason() uint32 {
	if x != nil {
		return x.RotationReason
	}
	return 0
}

// SubAuthority is a key the domain root delegates countersigning to
// (whitepaper Section 13.6). Covered by the DAR self-signature. Retired by
// setting effective_until; the entry is kept so earlier countersigs stay valid.
type SubAuthority struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Ed25519PublicKey []byte                 `protobuf:"bytes,1,opt,name=ed25519_public_key,json=ed25519PublicKey,proto3" json:"ed25519_public_key,omitempty"` // 32 bytes
	Scope            string                 `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`                                                 // "" = whole domain
	EffectiveFrom    int64                  `protobuf:"varint,3,opt,name=effective_from,json=effectiveFrom,proto3" json:"effective_from,omitempty"`           // Unix seconds
	EffectiveUntil   int64                  `protobuf:"varint,4,opt,name=effective_until,json=effectiveUntil,proto3" json:"effective_until,omitempty"`        // Unix seconds; 0 = open-ended
	Permissions      uint32                 `protobuf:"varint,5,opt,name=permissions,proto3" json:"permissions,omitempty"`                                    // carried-unenforced
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SubAuthority) Reset() {
	*x = SubAuthority{}
	mi := &file_identity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubAuthority) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubAuthority) ProtoMessage() {}

func (x *SubAuthority) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubAuthority.ProtoReflect.Descriptor instead.
func (*SubAuthority) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{3}
}

func (x *SubAuthority) GetEd25519PublicKey() []byte {
	if x != nil {
		return x.Ed25519PublicKey
	}
	return nil
}

func (x *SubAuthority) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *SubAuthority) GetEffectiveFrom() int64 {
	if x != nil {
		return x.EffectiveFrom
	}
	return 0
}

func (x *SubAuthority) GetEffectiveUntil() int64 {
	if x != nil {
		return x.EffectiveUntil
	}
	return 0
}

func (x *SubAuthority) GetPermissions() uint32 {
	if x != nil {
		return x.Permissions
	}
	return 0
}

// DomainAuthorityRecord declares a domain's authority key (DNS-proven) and the
// keys it authorizes to countersign addresses under the domain. Served by the
// domain's fleet and verified against the domain's DNS fingerprint anchor.
type DomainAuthorityRecord struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	Version                   uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Domain                    string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	AuthorityEd25519PublicKey []byte                 `protobuf:"bytes,3,opt,name=authority_ed25519_public_key,json=authorityEd25519PublicKey,proto3" json:"authority_ed25519_public_key,omitempty"` // 32 bytes — CURRENT root key
	AuthorityX25519PublicKey  []byte                 `protobuf:"bytes,4,opt,name=authority_x25519_public_key,json=authorityX25519PublicKey,proto3" json:"authority_x25519_public_key,omitempty"`    // 32 bytes — CURRENT root key
	AuthorityEffectiveFrom    int64                  `protobuf:"varint,5,opt,name=authority_effective_from,json=authorityEffectiveFrom,proto3" json:"authority_effective_from,omitempty"`           // Unix seconds — current key's start
	SupersededKeys            []*AuthorityKey        `protobuf:"bytes,6,rep,name=superseded_keys,json=supersededKeys,proto3" json:"superseded_keys,omitempty"`                                      // root rotation history
	SubAuthorities            []*SubAuthority        `protobuf:"bytes,7,rep,name=sub_authorities,json=subAuthorities,proto3" json:"sub_authorities,omitempty"`                                      // delegated signers (append-only)
	PolicyFlags               uint32                 `protobuf:"varint,8,opt,name=policy_flags,json=policyFlags,proto3" json:"policy_flags,omitempty"`                                              // carried-unenforced
	CreatedAt                 int64                  `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                                                    // Unix seconds
	Revision                  uint64                 `protobuf:"varint,10,opt,name=revision,proto3" json:"revision,omitempty"`                                                                      // monotonic; bumped on every republish
	SelfSignature             []byte                 `protobuf:"bytes,11,opt,name=self_signature,json=selfSignature,proto3" json:"self_signature,omitempty"`                                        // 64 bytes Ed25519 by CURRENT root key over fields 1-10,12-14
	// Unified Credential PKI: the domain's authority credentials (role "sub-authority",
	// any delegation depth) live here so one cached DAR fetch resolves any issuer. Each
	// is independently root/authority-signed; also covered by the DAR self-signature.
	AuthorityCredentials []*Credential `protobuf:"bytes,12,rep,name=authority_credentials,json=authorityCredentials,proto3" json:"authority_credentials,omitempty"`
	// Local-parts (case-insensitive) that may NOT be self-service registered on this domain —
	// seeded with a default set at genesis, then fully owner-customizable. A reserved address
	// requires the domain authority's countersignature to become usable. Covered by the DAR
	// self-signature. See whitepaper Section 13.
	ReservedLocalParts []string `protobuf:"bytes,13,rep,name=reserved_local_parts,json=reservedLocalParts,proto3" json:"reserved_local_parts,omitempty"`
	// fleet_domain: the fleet domain this mailbox domain defers hosting to (email's MX
	// delegation). Empty ⇒ the domain hosts its own nodes. This is the SIGNED mirror of the
	// DNS "fleet=" pointer (deferral hardening): a resolver enforces DNS fleet== this value,
	// fail-closed on mismatch, so the authorized fleet is cryptographically confirmed by the
	// domain's own root key, not merely DNS-asserted. Covered by the DAR self-signature.
	FleetDomain   string `protobuf:"bytes,14,opt,name=fleet_domain,json=fleetDomain,proto3" json:"fleet_domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DomainAuthorityRecord) Reset() {
	*x = DomainAuthorityRecord{}
	mi := &file_identity_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainAuthorityRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainAuthorityRecord) ProtoMessage() {}

func (x *DomainAuthorityRecord) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainAuthorityRecord.ProtoReflect.Descriptor instead.
func (*DomainAuthorityRecord) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{4}
}

func (x *DomainAuthorityRecord) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *DomainAuthorityRecord) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *DomainAuthorityRecord) GetAuthorityEd25519PublicKey() []byte {
	if x != nil {
		return x.AuthorityEd25519PublicKey
	}
	return nil
}

func (x *DomainAuthorityRecord) GetAuthorityX25519PublicKey() []byte {
	if x != nil {
		return x.AuthorityX25519PublicKey
	}
	return nil
}

func (x *DomainAuthorityRecord) GetAuthorityEffectiveFrom() int64 {
	if x != nil {
		return x.AuthorityEffectiveFrom
	}
	return 0
}

func (x *DomainAuthorityRecord) GetSupersededKeys() []*AuthorityKey {
	if x != nil {
		return x.SupersededKeys
	}
	return nil
}

func (x *DomainAuthorityRecord) GetSubAuthorities() []*SubAuthority {
	if x != nil {
		return x.SubAuthorities
	}
	return nil
}

func (x *DomainAuthorityRecord) GetPolicyFlags() uint32 {
	if x != nil {
		return x.PolicyFlags
	}
	return 0
}

func (x *DomainAuthorityRecord) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *DomainAuthorityRecord) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *DomainAuthorityRecord) GetSelfSignature() []byte {
	if x != nil {
		return x.SelfSignature
	}
	return nil
}

func (x *DomainAuthorityRecord) GetAuthorityCredentials() []*Credential {
	if x != nil {
		return x.AuthorityCredentials
	}
	return nil
}

func (x *DomainAuthorityRecord) GetReservedLocalParts() []string {
	if x != nil {
		return x.ReservedLocalParts
	}
	return nil
}

func (x *DomainAuthorityRecord) GetFleetDomain() string {
	if x != nil {
		return x.FleetDomain
	}
	return ""
}

// FleetNode is one node/relay in a fleet roster: its peer ID, where to dial it, and
// (informationally) what roles it serves. The node still proves its own membership
// Credential at /dmcn/join; the roster only advertises where to find it.
type FleetNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Multiaddrs    []string               `protobuf:"bytes,2,rep,name=multiaddrs,proto3" json:"multiaddrs,omitempty"`
	Roles         []string               `protobuf:"bytes,3,rep,name=roles,proto3" json:"roles,omitempty"` // node|bridge|... (informational)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FleetNode) Reset() {
	*x = FleetNode{}
	mi := &file_identity_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FleetNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FleetNode) ProtoMessage() {}

func (x *FleetNode) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FleetNode.ProtoReflect.Descriptor instead.
func (*FleetNode) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{5}
}

func (x *FleetNode) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *FleetNode) GetMultiaddrs() []string {
	if x != nil {
		return x.Multiaddrs
	}
	return nil
}

func (x *FleetNode) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

// FleetRoster is the fleet OWNER's root-signed, monotonic-revision list of the nodes
// that serve the fleet, anchored to the fleet domain's DNS fingerprint (its own DAR root
// key). It is the availability/discovery layer that replaces the DHT's provider records:
// a reader bootstraps from a few DNS "seed=" endpoints, fetches this roster from any of
// them, and learns the full authoritative node set (so discovery is not single-pinned).
// The roster's signature only vouches for "these nodes serve this fleet" — identity
// records and DARs remain trust-anchored to each mailbox domain, so a lying roster is an
// availability concern, never a forgery vector.
type FleetRoster struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	FleetDomain   string                 `protobuf:"bytes,2,opt,name=fleet_domain,json=fleetDomain,proto3" json:"fleet_domain,omitempty"` // the fleet domain whose root key signs this (its FP anchors it in DNS)
	Nodes         []*FleetNode           `protobuf:"bytes,3,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Revision      uint64                 `protobuf:"varint,4,opt,name=revision,proto3" json:"revision,omitempty"`                               // monotonic; bumped on every republish
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`            // Unix seconds; selects the root key that signed it
	SelfSignature []byte                 `protobuf:"bytes,6,opt,name=self_signature,json=selfSignature,proto3" json:"self_signature,omitempty"` // 64 bytes Ed25519 by the fleet domain root key over fields 1-5
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FleetRoster) Reset() {
	*x = FleetRoster{}
	mi := &file_identity_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FleetRoster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FleetRoster) ProtoMessage() {}

func (x *FleetRoster) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FleetRoster.ProtoReflect.Descriptor instead.
func (*FleetRoster) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{6}
}

func (x *FleetRoster) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *FleetRoster) GetFleetDomain() string {
	if x != nil {
		return x.FleetDomain
	}
	return ""
}

func (x *FleetRoster) GetNodes() []*FleetNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *FleetRoster) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *FleetRoster) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *FleetRoster) GetSelfSignature() []byte {
	if x != nil {
		return x.SelfSignature
	}
	return nil
}

// Credential is the unified DMCN membership credential. An authority countersigns a
// subject's Ed25519 public key, binding it to a domain with a set of roles, the roles
// it may itself issue (grants), and verifiable attributes. Presented at the join
// handshake (infra/clients) or stored per-address. Valid unless blocked — no mandatory
// expiry. See the Credential PKI plan.
type Credential struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Subject       []byte                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"` // subject Ed25519 pubkey (== peer ID for infra/clients; identity key for addresses)
	Domain        string                 `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`                                                                                 // role "address" only: local@domain
	Roles         []string               `protobuf:"bytes,5,rep,name=roles,proto3" json:"roles,omitempty"`                                                                                     // authority|sub-authority|node|bridge|client|address (combine)
	Grants        []string               `protobuf:"bytes,6,rep,name=grants,proto3" json:"grants,omitempty"`                                                                                   // roles this subject may ISSUE; "grant" = may issue grants-bearing creds
	Attributes    map[string]string      `protobuf:"bytes,7,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // multiaddr, ip, x25519 (onion key), ...
	IssuedAt      int64                  `protobuf:"varint,8,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`                                                              // Unix seconds
	NotAfter      int64                  `protobuf:"varint,9,opt,name=not_after,json=notAfter,proto3" json:"not_after,omitempty"`                                                              // Unix seconds; 0 = never expires
	Scope         string                 `protobuf:"bytes,10,opt,name=scope,proto3" json:"scope,omitempty"`                                                                                    // authority creds: subdomain scope ("" = whole domain)
	IssuerPub     []byte                 `protobuf:"bytes,11,opt,name=issuer_pub,json=issuerPub,proto3" json:"issuer_pub,omitempty"`                                                           // root, or an authority cred (any depth) whose grants cover this
	Signature     []byte                 `protobuf:"bytes,12,opt,name=signature,proto3" json:"signature,omitempty"`                                                                            // issuer Ed25519 sig over fields 1-11,13,14 (distinct ctx tag)
	RelayHints    []string               `protobuf:"bytes,13,rep,name=relay_hints,json=relayHints,proto3" json:"relay_hints,omitempty"`                                                        // role "routing" only: the authoritative, operator-signed mailbox relay hints
	EffectiveFrom int64                  `protobuf:"varint,14,opt,name=effective_from,json=effectiveFrom,proto3" json:"effective_from,omitempty"`                                              // Unix seconds; not-before (0 = no constraint, effective immediately). Validity window is [effective_from, not_after].
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Credential) Reset() {
	*x = Credential{}
	mi := &file_identity_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Credential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Credential) ProtoMessage() {}

func (x *Credential) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Credential.ProtoReflect.Descriptor instead.
func (*Credential) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{7}
}

func (x *Credential) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Credential) GetSubject() []byte {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *Credential) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Credential) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Credential) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *Credential) GetGrants() []string {
	if x != nil {
		return x.Grants
	}
	return nil
}

func (x *Credential) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *Credential) GetIssuedAt() int64 {
	if x != nil {
		return x.IssuedAt
	}
	return 0
}

func (x *Credential) GetNotAfter() int64 {
	if x != nil {
		return x.NotAfter
	}
	return 0
}

func (x *Credential) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *Credential) GetIssuerPub() []byte {
	if x != nil {
		return x.IssuerPub
	}
	return nil
}

func (x *Credential) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *Credential) GetRelayHints() []string {
	if x != nil {
		return x.RelayHints
	}
	return nil
}

func (x *Credential) GetEffectiveFrom() int64 {
	if x != nil {
		return x.EffectiveFrom
	}
	return 0
}

// CredentialBlock is one timestamped, root-signed revocation entry. A block is
// forward-only by default (creds with issued_at >= effective_from rejected); a
// compromised key invalidates ALL its signatures.
type CredentialBlock struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Pubkey           []byte                 `protobuf:"bytes,1,opt,name=pubkey,proto3" json:"pubkey,omitempty"`                                              // the blocked key
	EffectiveFrom    int64                  `protobuf:"varint,2,opt,name=effective_from,json=effectiveFrom,proto3" json:"effective_from,omitempty"`          // Unix seconds; creds issued_at >= this are rejected
	Compromised      bool                   `protobuf:"varint,3,opt,name=compromised,proto3" json:"compromised,omitempty"`                                   // true ⇒ invalidate ALL of the key's signatures
	CompromisedSince int64                  `protobuf:"varint,4,opt,name=compromised_since,json=compromisedSince,proto3" json:"compromised_since,omitempty"` // optional best-effort earlier cutoff
	CreatedAt        int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                      // Unix seconds
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CredentialBlock) Reset() {
	*x = CredentialBlock{}
	mi := &file_identity_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialBlock) ProtoMessage() {}

func (x *CredentialBlock) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialBlock.ProtoReflect.Descriptor instead.
func (*CredentialBlock) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{8}
}

func (x *CredentialBlock) GetPubkey() []byte {
	if x != nil {
		return x.Pubkey
	}
	return nil
}

func (x *CredentialBlock) GetEffectiveFrom() int64 {
	if x != nil {
		return x.EffectiveFrom
	}
	return 0
}

func (x *CredentialBlock) GetCompromised() bool {
	if x != nil {
		return x.Compromised
	}
	return false
}

func (x *CredentialBlock) GetCompromisedSince() int64 {
	if x != nil {
		return x.CompromisedSince
	}
	return 0
}

func (x *CredentialBlock) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// CredentialBlockList is the domain's root-signed blocklist, served as its own
// record so the DAR doesn't churn on every block.
type CredentialBlockList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Blocks        []*CredentialBlock     `protobuf:"bytes,2,rep,name=blocks,proto3" json:"blocks,omitempty"`
	Revision      uint64                 `protobuf:"varint,3,opt,name=revision,proto3" json:"revision,omitempty"`  // monotonic
	Signature     []byte                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"` // root Ed25519 sig over fields 1-3
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CredentialBlockList) Reset() {
	*x = CredentialBlockList{}
	mi := &file_identity_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialBlockList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialBlockList) ProtoMessage() {}

func (x *CredentialBlockList) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialBlockList.ProtoReflect.Descriptor instead.
func (*CredentialBlockList) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{9}
}

func (x *CredentialBlockList) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *CredentialBlockList) GetBlocks() []*CredentialBlock {
	if x != nil {
		return x.Blocks
	}
	return nil
}

func (x *CredentialBlockList) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *CredentialBlockList) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// CredentialBundle pairs a Credential with the DAR that anchors it (the unit exchanged at
// /dmcn/join and provisioning).
type CredentialBundle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Credential    *Credential            `protobuf:"bytes,1,opt,name=credential,proto3" json:"credential,omitempty"`
	Dar           *DomainAuthorityRecord `protobuf:"bytes,2,opt,name=dar,proto3" json:"dar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CredentialBundle) Reset() {
	*x = CredentialBundle{}
	mi := &file_identity_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialBundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialBundle) ProtoMessage() {}

func (x *CredentialBundle) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialBundle.ProtoReflect.Descriptor instead.
func (*CredentialBundle) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{10}
}

func (x *CredentialBundle) GetCredential() *Credential {
	if x != nil {
		return x.Credential
	}
	return nil
}

func (x *CredentialBundle) GetDar() *DomainAuthorityRecord {
	if x != nil {
		return x.Dar
	}
	return nil
}

// JoinRequest / JoinResponse carry the /dmcn/join handshake (Credential PKI). Each side
// presents its Credential plus the DAR that anchors it, so the peer can verify against a
// direct DNS resolution without a DHT lookup (works at cold-start / for foreign domains). A
// peer credentialed in SEVERAL domains (hosted multi-tenant) presents one bundle per domain in
// `bundles`; the singular credential/dar remain for single-domain peers (the primary bundle).
type JoinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Credential    *Credential            `protobuf:"bytes,1,opt,name=credential,proto3" json:"credential,omitempty"` // primary (single-domain compatibility)
	Dar           *DomainAuthorityRecord `protobuf:"bytes,2,opt,name=dar,proto3" json:"dar,omitempty"`
	Bundles       []*CredentialBundle    `protobuf:"bytes,3,rep,name=bundles,proto3" json:"bundles,omitempty"` // all of the peer's {credential, DAR}, one per domain
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRequest) Reset() {
	*x = JoinRequest{}
	mi := &file_identity_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequest) ProtoMessage() {}

func (x *JoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequest.ProtoReflect.Descriptor instead.
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{11}
}

func (x *JoinRequest) GetCredential() *Credential {
	if x != nil {
		return x.Credential
	}
	return nil
}

func (x *JoinRequest) GetDar() *DomainAuthorityRecord {
	if x != nil {
		return x.Dar
	}
	return nil
}

func (x *JoinRequest) GetBundles() []*CredentialBundle {
	if x != nil {
		return x.Bundles
	}
	return nil
}

type JoinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Credential    *Credential            `protobuf:"bytes,3,opt,name=credential,proto3" json:"credential,omitempty"` // responder's own primary credential (mutual join)
	Dar           *DomainAuthorityRecord `protobuf:"bytes,4,opt,name=dar,proto3" json:"dar,omitempty"`
	Bundles       []*CredentialBundle    `protobuf:"bytes,5,rep,name=bundles,proto3" json:"bundles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinResponse) Reset() {
	*x = JoinResponse{}
	mi := &file_identity_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinResponse) ProtoMessage() {}

func (x *JoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinResponse.ProtoReflect.Descriptor instead.
func (*JoinResponse) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{12}
}

func (x *JoinResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *JoinResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *JoinResponse) GetCredential() *Credential {
	if x != nil {
		return x.Credential
	}
	return nil
}

func (x *JoinResponse) GetDar() *DomainAuthorityRecord {
	if x != nil {
		return x.Dar
	}
	return nil
}

func (x *JoinResponse) GetBundles() []*CredentialBundle {
	if x != nil {
		return x.Bundles
	}
	return nil
}

// RemovedBinding tombstones a specific prior (address, user key) binding so the
// address can be re-bound to a new key. See whitepaper Section 13.3.
type RemovedBinding struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Ed25519PublicKey []byte                 `protobuf:"bytes,1,opt,name=ed25519_public_key,json=ed25519PublicKey,proto3" json:"ed25519_public_key,omitempty"` // 32 bytes — the offboarded user identity key
	RemovedAt        int64                  `protobuf:"varint,2,opt,name=removed_at,json=removedAt,proto3" json:"removed_at,omitempty"`                       // Unix seconds
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RemovedBinding) Reset() {
	*x = RemovedBinding{}
	mi := &file_identity_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemovedBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovedBinding) ProtoMessage() {}

func (x *RemovedBinding) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovedBinding.ProtoReflect.Descriptor instead.
func (*RemovedBinding) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{13}
}

func (x *RemovedBinding) GetEd25519PublicKey() []byte {
	if x != nil {
		return x.Ed25519PublicKey
	}
	return nil
}

func (x *RemovedBinding) GetRemovedAt() int64 {
	if x != nil {
		return x.RemovedAt
	}
	return 0
}

// AddressRemovalRecord is the root-signed, append-only list of removed bindings
// for one address, served by the domain's fleet. Only the domain root can
// publish one, so only root can free an address for re-binding.
type AddressRemovalRecord struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Version         uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Domain          string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	Address         string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	RemovedBindings []*RemovedBinding      `protobuf:"bytes,4,rep,name=removed_bindings,json=removedBindings,proto3" json:"removed_bindings,omitempty"`
	Revision        uint64                 `protobuf:"varint,5,opt,name=revision,proto3" json:"revision,omitempty"`                               // monotonic; bumped on every republish
	CreatedAt       int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`            // Unix seconds; selects the root key that signed it
	SelfSignature   []byte                 `protobuf:"bytes,7,opt,name=self_signature,json=selfSignature,proto3" json:"self_signature,omitempty"` // 64 bytes Ed25519 by the root key over fields 1-6
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AddressRemovalRecord) Reset() {
	*x = AddressRemovalRecord{}
	mi := &file_identity_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressRemovalRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressRemovalRecord) ProtoMessage() {}

func (x *AddressRemovalRecord) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressRemovalRecord.ProtoReflect.Descriptor instead.
func (*AddressRemovalRecord) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{14}
}

func (x *AddressRemovalRecord) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *AddressRemovalRecord) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *AddressRemovalRecord) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *AddressRemovalRecord) GetRemovedBindings() []*RemovedBinding {
	if x != nil {
		return x.RemovedBindings
	}
	return nil
}

func (x *AddressRemovalRecord) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *AddressRemovalRecord) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *AddressRemovalRecord) GetSelfSignature() []byte {
	if x != nil {
		return x.SelfSignature
	}
	return nil
}

// CompromisedKey marks a domain countersigning key (root or sub-authority) as
// compromised. Countersignatures by this key dated at/after compromised_at are
// rejected outright; those dated before are honored only until retention_until
// (a grace window for the domain to re-countersign affected identities with a
// fresh key), after which the key is fully distrusted — a backdate-proof cutoff,
// since an attacker holding the key could otherwise forge an earlier date.
type CompromisedKey struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Ed25519PublicKey []byte                 `protobuf:"bytes,1,opt,name=ed25519_public_key,json=ed25519PublicKey,proto3" json:"ed25519_public_key,omitempty"` // 32 bytes — the compromised countersigning key
	CompromisedAt    int64                  `protobuf:"varint,2,opt,name=compromised_at,json=compromisedAt,proto3" json:"compromised_at,omitempty"`           // Unix seconds — declared compromise time
	RetentionUntil   int64                  `protobuf:"varint,3,opt,name=retention_until,json=retentionUntil,proto3" json:"retention_until,omitempty"`        // Unix seconds — pre-compromise sigs honored until this; 0 = immediate full distrust
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CompromisedKey) Reset() {
	*x = CompromisedKey{}
	mi := &file_identity_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompromisedKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompromisedKey) ProtoMessage() {}

func (x *CompromisedKey) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompromisedKey.ProtoReflect.Descriptor instead.
func (*CompromisedKey) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{15}
}

func (x *CompromisedKey) GetEd25519PublicKey() []byte {
	if x != nil {
		return x.Ed25519PublicKey
	}
	return nil
}

func (x *CompromisedKey) GetCompromisedAt() int64 {
	if x != nil {
		return x.CompromisedAt
	}
	return 0
}

func (x *CompromisedKey) GetRetentionUntil() int64 {
	if x != nil {
		return x.RetentionUntil
	}
	return 0
}

// RelayDescriptor advertises a relay node's onion-routing key so senders can
// encrypt onion layers to it. Resolved from the node itself (GetRelayDescriptor)
// and signed by the node's libp2p identity key — which is recoverable from the
// peer ID itself, so the descriptor is self-anchoring (no external trust needed
// to bind the X25519 onion key to the peer). See whitepaper Section 15.4.
type RelayDescriptor struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PeerId          string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	X25519PublicKey []byte                 `protobuf:"bytes,2,opt,name=x25519_public_key,json=x25519PublicKey,proto3" json:"x25519_public_key,omitempty"` // 32 bytes — onion layer encryption key
	Multiaddrs      []string               `protobuf:"bytes,3,rep,name=multiaddrs,proto3" json:"multiaddrs,omitempty"`
	CreatedAt       int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Unix seconds
	Revision        uint64                 `protobuf:"varint,5,opt,name=revision,proto3" json:"revision,omitempty"`                    // monotonic; bumped on republish
	Signature       []byte                 `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`                   // node libp2p-key sig over fields 1-5,7 (not the countersig)
	// Domain binding (DMCN PKI / domain-anchored federation). The node self-asserts
	// the domain it serves (field 7, covered by the self-signature); the domain
	// authority — root or a PermVouchNode sub-authority — countersigns the stable
	// {domain, peer_id, x25519} binding (fields 8-10). The countersignature covers
	// only that binding, NOT multiaddrs/revision, so it survives liveness re-publish.
	Domain                    string `protobuf:"bytes,7,opt,name=domain,proto3" json:"domain,omitempty"`                                                                           // domain this node belongs to (e.g. "example.com")
	DomainCountersignature    []byte `protobuf:"bytes,8,opt,name=domain_countersignature,json=domainCountersignature,proto3" json:"domain_countersignature,omitempty"`             // 64 bytes Ed25519 over the binding
	DomainCountersignedAt     int64  `protobuf:"varint,9,opt,name=domain_countersigned_at,json=domainCountersignedAt,proto3" json:"domain_countersigned_at,omitempty"`             // Unix seconds; authenticated countersign time
	DomainCountersignerPubkey []byte `protobuf:"bytes,10,opt,name=domain_countersigner_pubkey,json=domainCountersignerPubkey,proto3" json:"domain_countersigner_pubkey,omitempty"` // 32 bytes Ed25519 of the root/sub-authority signer
	// credential (Credential PKI): the node's membership credential (role "node"),
	// so onion route selection can verify a relay's trust by credential without
	// connecting to it. Replaces the domain_countersignature fields above. Subject is
	// the peer ID's key, so it can't be swapped onto another descriptor.
	Credential    *Credential `protobuf:"bytes,11,opt,name=credential,proto3" json:"credential,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayDescriptor) Reset() {
	*x = RelayDescriptor{}
	mi := &file_identity_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayDescriptor) ProtoMessage() {}

func (x *RelayDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayDescriptor.ProtoReflect.Descriptor instead.
func (*RelayDescriptor) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{16}
}

func (x *RelayDescriptor) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *RelayDescriptor) GetX25519PublicKey() []byte {
	if x != nil {
		return x.X25519PublicKey
	}
	return nil
}

func (x *RelayDescriptor) GetMultiaddrs() []string {
	if x != nil {
		return x.Multiaddrs
	}
	return nil
}

func (x *RelayDescriptor) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *RelayDescriptor) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *RelayDescriptor) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *RelayDescriptor) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *RelayDescriptor) GetDomainCountersignature() []byte {
	if x != nil {
		return x.DomainCountersignature
	}
	return nil
}

func (x *RelayDescriptor) GetDomainCountersignedAt() int64 {
	if x != nil {
		return x.DomainCountersignedAt
	}
	return 0
}

func (x *RelayDescriptor) GetDomainCountersignerPubkey() []byte {
	if x != nil {
		return x.DomainCountersignerPubkey
	}
	return nil
}

func (x *RelayDescriptor) GetCredential() *Credential {
	if x != nil {
		return x.Credential
	}
	return nil
}

// KeyCompromiseRecord is the root-signed, append-only list of compromised
// countersigning keys for a domain, served by the domain's fleet. Only the
// domain root can publish one. See whitepaper Section 13 (key compromise).
type KeyCompromiseRecord struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Version         uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Domain          string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	CompromisedKeys []*CompromisedKey      `protobuf:"bytes,3,rep,name=compromised_keys,json=compromisedKeys,proto3" json:"compromised_keys,omitempty"`
	Revision        uint64                 `protobuf:"varint,4,opt,name=revision,proto3" json:"revision,omitempty"`                               // monotonic; bumped on every republish
	CreatedAt       int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`            // Unix seconds; selects the root key that signed it
	SelfSignature   []byte                 `protobuf:"bytes,6,opt,name=self_signature,json=selfSignature,proto3" json:"self_signature,omitempty"` // 64 bytes Ed25519 by the root key over fields 1-5
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *KeyCompromiseRecord) Reset() {
	*x = KeyCompromiseRecord{}
	mi := &file_identity_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyCompromiseRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyCompromiseRecord) ProtoMessage() {}

func (x *KeyCompromiseRecord) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyCompromiseRecord.ProtoReflect.Descriptor instead.
func (*KeyCompromiseRecord) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{17}
}

func (x *KeyCompromiseRecord) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *KeyCompromiseRecord) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *KeyCompromiseRecord) GetCompromisedKeys() []*CompromisedKey {
	if x != nil {
		return x.CompromisedKeys
	}
	return nil
}

func (x *KeyCompromiseRecord) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *KeyCompromiseRecord) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *KeyCompromiseRecord) GetSelfSignature() []byte {
	if x != nil {
		return x.SelfSignature
	}
	return nil
}

var File_identity_proto protoreflect.FileDescriptor

const file_identity_proto_rawDesc = "" +
	"\n" +
	"\x0eidentity.proto\x12\rdmcn.identity\"\xe0\x02\n" +
	"\x11AttestationRecord\x12)\n" +
	"\x10attester_address\x18\x01 \x01(\tR\x0fattesterAddress\x12'\n" +
	"\x0fattester_pubkey\x18\x02 \x01(\fR\x0eattesterPubkey\x12'\n" +
	"\x0fsubject_address\x18\x03 \x01(\tR\x0esubjectAddress\x12%\n" +
	"\x0esubject_pubkey\x18\x04 \x01(\fR\rsubjectPubkey\x12I\n" +
	"\x10attestation_type\x18\x05 \x01(\x0e2\x1e.dmcn.identity.AttestationTypeR\x0fattestationType\x12\x1f\n" +
	"\vattested_at\x18\x06 \x01(\x03R\n" +
	"attestedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\a \x01(\x03R\texpiresAt\x12\x1c\n" +
	"\tsignature\x18\b \x01(\fR\tsignature\"\xbe\b\n" +
	"\x0eIdentityRecord\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12,\n" +
	"\x12ed25519_public_key\x18\x03 \x01(\fR\x10ed25519PublicKey\x12*\n" +
	"\x11x25519_public_key\x18\x04 \x01(\fR\x0fx25519PublicKey\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\x03R\texpiresAt\x12\x1f\n" +
	"\vrelay_hints\x18\a \x03(\tR\n" +
	"relayHints\x12L\n" +
	"\x11verification_tier\x18\b \x01(\x0e2\x1f.dmcn.identity.VerificationTierR\x10verificationTier\x12D\n" +
	"\fattestations\x18\t \x03(\v2 .dmcn.identity.AttestationRecordR\fattestations\x12%\n" +
	"\x0eself_signature\x18\n" +
	" \x01(\fR\rselfSignature\x12+\n" +
	"\x11bridge_capability\x18\x13 \x01(\bR\x10bridgeCapability\x127\n" +
	"\x17domain_countersignature\x18\x14 \x01(\fR\x16domainCountersignature\x126\n" +
	"\x17domain_countersigned_at\x18\x15 \x01(\x03R\x15domainCountersignedAt\x12>\n" +
	"\x1bdomain_countersigner_pubkey\x18\x16 \x01(\fR\x19domainCountersignerPubkey\x12#\n" +
	"\rrequire_onion\x18\x17 \x01(\bR\frequireOnion\x12H\n" +
	"\x12address_credential\x18\x18 \x01(\v2\x19.dmcn.identity.CredentialR\x11addressCredential\x12H\n" +
	"\x12routing_credential\x18\x19 \x01(\v2\x19.dmcn.identity.CredentialR\x11routingCredential\x12\x1a\n" +
	"\brevision\x18\x1a \x01(\x04R\brevision\x12L\n" +
	"\x14operator_credentials\x18\x1c \x03(\v2\x19.dmcn.identity.CredentialR\x13operatorCredentialsJ\x04\b\v\x10\fJ\x04\b\f\x10\rJ\x04\b\r\x10\x0eJ\x04\b\x0e\x10\x0fJ\x04\b\x0f\x10\x10J\x04\b\x10\x10\x11J\x04\b\x11\x10\x12J\x04\b\x12\x10\x13J\x04\b\x1b\x10\x1cR\x06claimsR\rclaim_recordsR\x06policyR\fpolicy_flagsR\x0fguardian_policyR\x0frate_credential\"\xb8\x01\n" +
	"\fAuthorityKey\x12,\n" +
	"\x12ed25519_public_key\x18\x01 \x01(\fR\x10ed25519PublicKey\x12*\n" +
	"\x11x25519_public_key\x18\x02 \x01(\fR\x0fx25519PublicKey\x12%\n" +
	"\x0eeffective_from\x18\x03 \x01(\x03R\reffectiveFrom\x12'\n" +
	"\x0frotation_reason\x18\x04 \x01(\rR\x0erotationReason\"\xc4\x01\n" +
	"\fSubAuthority\x12,\n" +
	"\x12ed25519_public_key\x18\x01 \x01(\fR\x10ed25519PublicKey\x12\x14\n" +
	"\x05scope\x18\x02 \x01(\tR\x05scope\x12%\n" +
	"\x0eeffective_from\x18\x03 \x01(\x03R\reffectiveFrom\x12'\n" +
	"\x0feffective_until\x18\x04 \x01(\x03R\x0eeffectiveUntil\x12 \n" +
	"\vpermissions\x18\x05 \x01(\rR\vpermissions\"\xb9\x05\n" +
	"\x15DomainAuthorityRecord\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\x12?\n" +
	"\x1cauthority_ed25519_public_key\x18\x03 \x01(\fR\x19authorityEd25519PublicKey\x12=\n" +
	"\x1bauthority_x25519_public_key\x18\x04 \x01(\fR\x18authorityX25519PublicKey\x128\n" +
	"\x18authority_effective_from\x18\x05 \x01(\x03R\x16authorityEffectiveFrom\x12D\n" +
	"\x0fsuperseded_keys\x18\x06 \x03(\v2\x1b.dmcn.identity.AuthorityKeyR\x0esupersededKeys\x12D\n" +
	"\x0fsub_authorities\x18\a \x03(\v2\x1b.dmcn.identity.SubAuthorityR\x0esubAuthorities\x12!\n" +
	"\fpolicy_flags\x18\b \x01(\rR\vpolicyFlags\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\x03R\tcreatedAt\x12\x1a\n" +
	"\brevision\x18\n" +
	" \x01(\x04R\brevision\x12%\n" +
	"\x0eself_signature\x18\v \x01(\fR\rselfSignature\x12N\n" +
	"\x15authority_credentials\x18\f \x03(\v2\x19.dmcn.identity.CredentialR\x14authorityCredentials\x120\n" +
	"\x14reserved_local_parts\x18\r \x03(\tR\x12reservedLocalParts\x12!\n" +
	"\ffleet_domain\x18\x0e \x01(\tR\vfleetDomain\"Z\n" +
	"\tFleetNode\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12\x1e\n" +
	"\n" +
	"multiaddrs\x18\x02 \x03(\tR\n" +
	"multiaddrs\x12\x14\n" +
	"\x05roles\x18\x03 \x03(\tR\x05roles\"\xdc\x01\n" +
	"\vFleetRoster\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12!\n" +
	"\ffleet_domain\x18\x02 \x01(\tR\vfleetDomain\x12.\n" +
	"\x05nodes\x18\x03 \x03(\v2\x18.dmcn.identity.FleetNodeR\x05nodes\x12\x1a\n" +
	"\brevision\x18\x04 \x01(\x04R\brevision\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12%\n" +
	"\x0eself_signature\x18\x06 \x01(\fR\rselfSignature\"\x91\x04\n" +
	"\n" +
	"Credential\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x18\n" +
	"\asubject\x18\x02 \x01(\fR\asubject\x12\x16\n" +
	"\x06domain\x18\x03 \x01(\tR\x06domain\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12\x14\n" +
	"\x05roles\x18\x05 \x03(\tR\x05roles\x12\x16\n" +
	"\x06grants\x18\x06 \x03(\tR\x06grants\x12I\n" +
	"\n" +
	"attributes\x18\a \x03(\v2).dmcn.identity.Credential.AttributesEntryR\n" +
	"attributes\x12\x1b\n" +
	"\tissued_at\x18\b \x01(\x03R\bissuedAt\x12\x1b\n" +
	"\tnot_after\x18\t \x01(\x03R\bnotAfter\x12\x14\n" +
	"\x05scope\x18\n" +
	" \x01(\tR\x05scope\x12\x1d\n" +
	"\n" +
	"issuer_pub\x18\v \x01(\fR\tissuerPub\x12\x1c\n" +
	"\tsignature\x18\f \x01(\fR\tsignature\x12\x1f\n" +
	"\vrelay_hints\x18\r \x03(\tR\n" +
	"relayHints\x12%\n" +
	"\x0eeffective_from\x18\x0e \x01(\x03R\reffectiveFrom\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01J\x04\b\x0f\x10\x10R\n" +
	"rate_steps\"\xbe\x01\n" +
	"\x0fCredentialBlock\x12\x16\n" +
	"\x06pubkey\x18\x01 \x01(\fR\x06pubkey\x12%\n" +
	"\x0eeffective_from\x18\x02 \x01(\x03R\reffectiveFrom\x12 \n" +
	"\vcompromised\x18\x03 \x01(\bR\vcompromised\x12+\n" +
	"\x11compromised_since\x18\x04 \x01(\x03R\x10compromisedSince\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\"\x9f\x01\n" +
	"\x13CredentialBlockList\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x126\n" +
	"\x06blocks\x18\x02 \x03(\v2\x1e.dmcn.identity.CredentialBlockR\x06blocks\x12\x1a\n" +
	"\brevision\x18\x03 \x01(\x04R\brevision\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\fR\tsignature\"\x85\x01\n" +
	"\x10CredentialBundle\x129\n" +
	"\n" +
	"credential\x18\x01 \x01(\v2\x19.dmcn.identity.CredentialR\n" +
	"credential\x126\n" +
	"\x03dar\x18\x02 \x01(\v2$.dmcn.identity.DomainAuthorityRecordR\x03dar\"\xbb\x01\n" +
	"\vJoinRequest\x129\n" +
	"\n" +
	"credential\x18\x01 \x01(\v2\x19.dmcn.identity.CredentialR\n" +
	"credential\x126\n" +
	"\x03dar\x18\x02 \x01(\v2$.dmcn.identity.DomainAuthorityRecordR\x03dar\x129\n" +
	"\abundles\x18\x03 \x03(\v2\x1f.dmcn.identity.CredentialBundleR\abundles\"\xee\x01\n" +
	"\fJoinResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x129\n" +
	"\n" +
	"credential\x18\x03 \x01(\v2\x19.dmcn.identity.CredentialR\n" +
	"credential\x126\n" +
	"\x03dar\x18\x04 \x01(\v2$.dmcn.identity.DomainAuthorityRecordR\x03dar\x129\n" +
	"\abundles\x18\x05 \x03(\v2\x1f.dmcn.identity.CredentialBundleR\abundles\"]\n" +
	"\x0eRemovedBinding\x12,\n" +
	"\x12ed25519_public_key\x18\x01 \x01(\fR\x10ed25519PublicKey\x12\x1d\n" +
	"\n" +
	"removed_at\x18\x02 \x01(\x03R\tremovedAt\"\x8e\x02\n" +
	"\x14AddressRemovalRecord\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12H\n" +
	"\x10removed_bindings\x18\x04 \x03(\v2\x1d.dmcn.identity.RemovedBindingR\x0fremovedBindings\x12\x1a\n" +
	"\brevision\x18\x05 \x01(\x04R\brevision\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\x12%\n" +
	"\x0eself_signature\x18\a \x01(\fR\rselfSignature\"\x8e\x01\n" +
	"\x0eCompromisedKey\x12,\n" +
	"\x12ed25519_public_key\x18\x01 \x01(\fR\x10ed25519PublicKey\x12%\n" +
	"\x0ecompromised_at\x18\x02 \x01(\x03R\rcompromisedAt\x12'\n" +
	"\x0fretention_until\x18\x03 \x01(\x03R\x0eretentionUntil\"\xd3\x03\n" +
	"\x0fRelayDescriptor\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12*\n" +
	"\x11x25519_public_key\x18\x02 \x01(\fR\x0fx25519PublicKey\x12\x1e\n" +
	"\n" +
	"multiaddrs\x18\x03 \x03(\tR\n" +
	"multiaddrs\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\x12\x1a\n" +
	"\brevision\x18\x05 \x01(\x04R\brevision\x12\x1c\n" +
	"\tsignature\x18\x06 \x01(\fR\tsignature\x12\x16\n" +
	"\x06domain\x18\a \x01(\tR\x06domain\x127\n" +
	"\x17domain_countersignature\x18\b \x01(\fR\x16domainCountersignature\x126\n" +
	"\x17domain_countersigned_at\x18\t \x01(\x03R\x15domainCountersignedAt\x12>\n" +
	"\x1bdomain_countersigner_pubkey\x18\n" +
	" \x01(\fR\x19domainCountersignerPubkey\x129\n" +
	"\n" +
	"credential\x18\v \x01(\v2\x19.dmcn.identity.CredentialR\n" +
	"credential\"\xf3\x01\n" +
	"\x13KeyCompromiseRecord\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\x12H\n" +
	"\x10compromised_keys\x18\x03 \x03(\v2\x1d.dmcn.identity.CompromisedKeyR\x0fcompromisedKeys\x12\x1a\n" +
	"\brevision\x18\x04 \x01(\x04R\brevision\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12%\n" +
	"\x0eself_signature\x18\x06 \x01(\fR\rselfSignature*\x9b\x01\n" +
	"\x10VerificationTier\x12 \n" +
	"\x1cVERIFICATION_TIER_UNVERIFIED\x10\x00\x12 \n" +
	"\x1cVERIFICATION_TIER_DOMAIN_DNS\x10\x02\x12\x1a\n" +
	"\x16VERIFICATION_TIER_DANE\x10\x03\"\x04\b\x01\x10\x01*!VERIFICATION_TIER_PROVIDER_HOSTED*\xb8\x01\n" +
	"\x0fAttestationType\x12 \n" +
	"\x1cATTESTATION_TYPE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aATTESTATION_TYPE_IN_PERSON\x10\x01\x12 \n" +
	"\x1cATTESTATION_TYPE_FINGERPRINT\x10\x02\x12\x1c\n" +
	"\x18ATTESTATION_TYPE_NETWORK\x10\x03\x12#\n" +
	"\x1fATTESTATION_TYPE_ORGANISATIONAL\x10\x04B-Z+github.com/mertenvg/open-dmcn/dmcnpb;dmcnpbb\x06proto3"

var (
	file_identity_proto_rawDescOnce sync.Once
	file_identity_proto_rawDescData []byte
)

func file_identity_proto_rawDescGZIP() []byte {
	file_identity_proto_rawDescOnce.Do(func() {
		file_identity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_identity_proto_rawDesc), len(file_identity_proto_rawDesc)))
	})
	return file_identity_proto_rawDescData
}

var file_identity_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_identity_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_identity_proto_goTypes = []any{
	(VerificationTier)(0),         // 0: dmcn.identity.VerificationTier
	(AttestationType)(0),          // 1: dmcn.identity.AttestationType
	(*AttestationRecord)(nil),     // 2: dmcn.identity.AttestationRecord
	(*IdentityRecord)(nil),        // 3: dmcn.identity.IdentityRecord
	(*AuthorityKey)(nil),          // 4: dmcn.identity.AuthorityKey
	(*SubAuthority)(nil),          // 5: dmcn.identity.SubAuthority
	(*DomainAuthorityRecord)(nil), // 6: dmcn.identity.DomainAuthorityRecord
	(*FleetNode)(nil),             // 7: dmcn.identity.FleetNode
	(*FleetRoster)(nil),           // 8: dmcn.identity.FleetRoster
	(*Credential)(nil),            // 9: dmcn.identity.Credential
	(*CredentialBlock)(nil),       // 10: dmcn.identity.CredentialBlock
	(*CredentialBlockList)(nil),   // 11: dmcn.identity.CredentialBlockList
	(*CredentialBundle)(nil),      // 12: dmcn.identity.CredentialBundle
	(*JoinRequest)(nil),           // 13: dmcn.identity.JoinRequest
	(*JoinResponse)(nil),          // 14: dmcn.identity.JoinResponse
	(*RemovedBinding)(nil),        // 15: dmcn.identity.RemovedBinding
	(*AddressRemovalRecord)(nil),  // 16: dmcn.identity.AddressRemovalRecord
	(*CompromisedKey)(nil),        // 17: dmcn.identity.CompromisedKey
	(*RelayDescriptor)(nil),       // 18: dmcn.identity.RelayDescriptor
	(*KeyCompromiseRecord)(nil),   // 19: dmcn.identity.KeyCompromiseRecord
	nil,                           // 20: dmcn.identity.Credential.AttributesEntry
}
var file_identity_proto_depIdxs = []int32{
	1,  // 0: dmcn.identity.AttestationRecord.attestation_type:type_name -> dmcn.identity.AttestationType
	0,  // 1: dmcn.identity.IdentityRecord.verification_tier:type_name -> dmcn.identity.VerificationTier
	2,  // 2: dmcn.identity.IdentityRecord.attestations:type_name -> dmcn.identity.AttestationRecord
	9,  // 3: dmcn.identity.IdentityRecord.address_credential:type_name -> dmcn.identity.Credential
	9,  // 4: dmcn.identity.IdentityRecord.routing_credential:type_name -> dmcn.identity.Credential
	9,  // 5: dmcn.identity.IdentityRecord.operator_credentials:type_name -> dmcn.identity.Credential
	4,  // 6: dmcn.identity.DomainAuthorityRecord.superseded_keys:type_name -> dmcn.identity.AuthorityKey
	5,  // 7: dmcn.identity.DomainAuthorityRecord.sub_authorities:type_name -> dmcn.identity.SubAuthority
	9,  // 8: dmcn.identity.DomainAuthorityRecord.authority_credentials:type_name -> dmcn.identity.Credential
	7,  // 9: dmcn.identity.FleetRoster.nodes:type_name -> dmcn.identity.FleetNode
	20, // 10: dmcn.identity.Credential.attributes:type_name -> dmcn.identity.Credential.AttributesEntry
	10, // 11: dmcn.identity.CredentialBlockList.blocks:type_name -> dmcn.identity.CredentialBlock
	9,  // 12: dmcn.identity.CredentialBundle.credential:type_name -> dmcn.identity.Credential
	6,  // 13: dmcn.identity.CredentialBundle.dar:type_name -> dmcn.identity.DomainAuthorityRecord
	9,  // 14: dmcn.identity.JoinRequest.credential:type_name -> dmcn.identity.Credential
	6,  // 15: dmcn.identity.JoinRequest.dar:type_name -> dmcn.identity.DomainAuthorityRecord
	12, // 16: dmcn.identity.JoinRequest.bundles:type_name -> dmcn.identity.CredentialBundle
	9,  // 17: dmcn.identity.JoinResponse.credential:type_name -> dmcn.identity.Credential
	6,  // 18: dmcn.identity.JoinResponse.dar:type_name -> dmcn.identity.DomainAuthorityRecord
	12, // 19: dmcn.identity.JoinResponse.bundles:type_name -> dmcn.identity.CredentialBundle
	15, // 20: dmcn.identity.AddressRemovalRecord.removed_bindings:type_name -> dmcn.identity.RemovedBinding
	9,  // 21: dmcn.identity.RelayDescriptor.credential:type_name -> dmcn.identity.Credential
	17, // 22: dmcn.identity.KeyCompromiseRecord.compromised_keys:type_name -> dmcn.identity.CompromisedKey
	23, // [23:23] is the sub-list for method output_type
	23, // [23:23] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_identity_proto_init() }
func file_identity_proto_init() {
	if File_identity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_identity_proto_rawDesc), len(file_identity_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_identity_proto_goTypes,
		DependencyIndexes: file_identity_proto_depIdxs,
		EnumInfos:         file_identity_proto_enumTypes,
		MessageInfos:      file_identity_proto_msgTypes,
	}.Build()
	File_identity_proto = out.File
	file_identity_proto_goTypes = nil
	file_identity_proto_depIdxs = nil
}
