// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: message.proto

package dmcnpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MessageBody holds the content of a message.
// See whitepaper Section 15.3.1.
type MessageBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentType   string                 `protobuf:"bytes,1,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"` // MIME type, e.g. "text/plain"
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`                            // UTF-8 encoded body text
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageBody) Reset() {
	*x = MessageBody{}
	mi := &file_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageBody) ProtoMessage() {}

func (x *MessageBody) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageBody.ProtoReflect.Descriptor instead.
func (*MessageBody) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

func (x *MessageBody) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *MessageBody) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

// AttachmentRecord describes an attachment within a message.
// See whitepaper Section 15.3.1.
type AttachmentRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttachmentId  []byte                 `protobuf:"bytes,1,opt,name=attachment_id,json=attachmentId,proto3" json:"attachment_id,omitempty"` // 16 bytes UUID
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"` // MIME type
	SizeBytes     uint64                 `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	ContentHash   []byte                 `protobuf:"bytes,5,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"` // 32 bytes SHA-256 of plaintext content
	Content       []byte                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`                            // attachment content (encrypted separately)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachmentRecord) Reset() {
	*x = AttachmentRecord{}
	mi := &file_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachmentRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachmentRecord) ProtoMessage() {}

func (x *AttachmentRecord) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachmentRecord.ProtoReflect.Descriptor instead.
func (*AttachmentRecord) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{1}
}

func (x *AttachmentRecord) GetAttachmentId() []byte {
	if x != nil {
		return x.AttachmentId
	}
	return nil
}

func (x *AttachmentRecord) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *AttachmentRecord) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *AttachmentRecord) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *AttachmentRecord) GetContentHash() []byte {
	if x != nil {
		return x.ContentHash
	}
	return nil
}

func (x *AttachmentRecord) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

// PlaintextMessage represents a composed message before signing or encryption.
// See whitepaper Section 15.3.1.
type PlaintextMessage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Version          uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	MessageId        []byte                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"` // 16 bytes UUID
	ThreadId         []byte                 `protobuf:"bytes,3,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`    // 16 bytes UUID
	SenderAddress    string                 `protobuf:"bytes,4,opt,name=sender_address,json=senderAddress,proto3" json:"sender_address,omitempty"`
	SenderPublicKey  []byte                 `protobuf:"bytes,5,opt,name=sender_public_key,json=senderPublicKey,proto3" json:"sender_public_key,omitempty"` // 32 bytes Ed25519
	RecipientAddress string                 `protobuf:"bytes,6,opt,name=recipient_address,json=recipientAddress,proto3" json:"recipient_address,omitempty"`
	SentAt           int64                  `protobuf:"varint,7,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"` // Unix seconds
	Subject          string                 `protobuf:"bytes,8,opt,name=subject,proto3" json:"subject,omitempty"`
	Body             *MessageBody           `protobuf:"bytes,9,opt,name=body,proto3" json:"body,omitempty"`
	Attachments      []*AttachmentRecord    `protobuf:"bytes,10,rep,name=attachments,proto3" json:"attachments,omitempty"`
	ReplyToId        []byte                 `protobuf:"bytes,11,opt,name=reply_to_id,json=replyToId,proto3" json:"reply_to_id,omitempty"` // 16 bytes UUID; empty = not a reply
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PlaintextMessage) Reset() {
	*x = PlaintextMessage{}
	mi := &file_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaintextMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaintextMessage) ProtoMessage() {}

func (x *PlaintextMessage) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaintextMessage.ProtoReflect.Descriptor instead.
func (*PlaintextMessage) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{2}
}

func (x *PlaintextMessage) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *PlaintextMessage) GetMessageId() []byte {
	if x != nil {
		return x.MessageId
	}
	return nil
}

func (x *PlaintextMessage) GetThreadId() []byte {
	if x != nil {
		return x.ThreadId
	}
	return nil
}

func (x *PlaintextMessage) GetSenderAddress() string {
	if x != nil {
		return x.SenderAddress
	}
	return ""
}

func (x *PlaintextMessage) GetSenderPublicKey() []byte {
	if x != nil {
		return x.SenderPublicKey
	}
	return nil
}

func (x *PlaintextMessage) GetRecipientAddress() string {
	if x != nil {
		return x.RecipientAddress
	}
	return ""
}

func (x *PlaintextMessage) GetSentAt() int64 {
	if x != nil {
		return x.SentAt
	}
	return 0
}

func (x *PlaintextMessage) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *PlaintextMessage) GetBody() *MessageBody {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *PlaintextMessage) GetAttachments() []*AttachmentRecord {
	if x != nil {
		return x.Attachments
	}
	return nil
}

func (x *PlaintextMessage) GetReplyToId() []byte {
	if x != nil {
		return x.ReplyToId
	}
	return nil
}

// SignedMessage wraps a PlaintextMessage with the sender's Ed25519 signature.
// See whitepaper Section 15.3.2.
type SignedMessage struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Plaintext       *PlaintextMessage      `protobuf:"bytes,1,opt,name=plaintext,proto3" json:"plaintext,omitempty"`
	SenderSignature []byte                 `protobuf:"bytes,2,opt,name=sender_signature,json=senderSignature,proto3" json:"sender_signature,omitempty"` // 64 bytes Ed25519 sig over canonical serialization of plaintext
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SignedMessage) Reset() {
	*x = SignedMessage{}
	mi := &file_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedMessage) ProtoMessage() {}

func (x *SignedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedMessage.ProtoReflect.Descriptor instead.
func (*SignedMessage) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{3}
}

func (x *SignedMessage) GetPlaintext() *PlaintextMessage {
	if x != nil {
		return x.Plaintext
	}
	return nil
}

func (x *SignedMessage) GetSenderSignature() []byte {
	if x != nil {
		return x.SenderSignature
	}
	return nil
}

// MessageHeader is the small, previewable part of a message — who/what/when plus
// a commitment (body_hash) to the body. Encrypted and signed independently of the
// body so a recipient can preview their inbox (LIST) and trust it without
// downloading the (potentially large) body.
type MessageHeader struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Version         uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	MessageId       []byte                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"` // 16 bytes UUID
	ThreadId        []byte                 `protobuf:"bytes,3,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`    // 16 bytes UUID
	SenderAddress   string                 `protobuf:"bytes,4,opt,name=sender_address,json=senderAddress,proto3" json:"sender_address,omitempty"`
	SenderPublicKey []byte                 `protobuf:"bytes,5,opt,name=sender_public_key,json=senderPublicKey,proto3" json:"sender_public_key,omitempty"` // 32 bytes Ed25519
	// Per-envelope routing/primary recipient of THIS copy (a single address).
	// Distinct from the `to` list below: `recipient_address` labels who this
	// particular envelope copy was addressed to (recipient copy = that recipient;
	// Sent self-copy = the sender's own address), while `to`/`cc` carry the full
	// shared audience visible to everyone.
	RecipientAddress string `protobuf:"bytes,6,opt,name=recipient_address,json=recipientAddress,proto3" json:"recipient_address,omitempty"`
	SentAt           int64  `protobuf:"varint,7,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"` // Unix seconds
	Subject          string `protobuf:"bytes,8,opt,name=subject,proto3" json:"subject,omitempty"`
	AttachmentCount  uint32 `protobuf:"varint,9,opt,name=attachment_count,json=attachmentCount,proto3" json:"attachment_count,omitempty"`
	BodySize         uint64 `protobuf:"varint,10,opt,name=body_size,json=bodySize,proto3" json:"body_size,omitempty"`     // plaintext body size, for UI
	Snippet          string `protobuf:"bytes,11,opt,name=snippet,proto3" json:"snippet,omitempty"`                        // optional short preview of the body
	ReplyToId        []byte `protobuf:"bytes,12,opt,name=reply_to_id,json=replyToId,proto3" json:"reply_to_id,omitempty"` // 16 bytes UUID; empty = not a reply
	BodyHash         []byte `protobuf:"bytes,13,opt,name=body_hash,json=bodyHash,proto3" json:"body_hash,omitempty"`      // 32 bytes SHA-256 over canonical MessageContent
	// Content address of the body ciphertext blob (body_nonce||encrypted_body||body_tag):
	// CIDv1(raw, sha2-256), 36 bytes. Signed (covered by the header signature), so a
	// verified header commits to the exact ciphertext blob, keylessly. Empty pre-feature.
	BodyContentAddress []byte `protobuf:"bytes,14,opt,name=body_content_address,json=bodyContentAddress,proto3" json:"body_content_address,omitempty"`
	// Full recipient lists, signature-protected and visible to every recipient of
	// this envelope. `to`/`cc` are identical across all recipients' copies. `bcc` is
	// only populated on the sender's own "Sent" self-copy; every recipient copy (To,
	// Cc, and Bcc recipients alike) carries an EMPTY bcc, so a Bcc recipient is never
	// revealed. Empty repeated fields are omitted by deterministic marshaling, so a
	// recipient copy with no bcc is byte-identical to one that never set it.
	To            []string `protobuf:"bytes,15,rep,name=to,proto3" json:"to,omitempty"`
	Cc            []string `protobuf:"bytes,16,rep,name=cc,proto3" json:"cc,omitempty"`
	Bcc           []string `protobuf:"bytes,17,rep,name=bcc,proto3" json:"bcc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageHeader) Reset() {
	*x = MessageHeader{}
	mi := &file_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageHeader) ProtoMessage() {}

func (x *MessageHeader) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageHeader.ProtoReflect.Descriptor instead.
func (*MessageHeader) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{4}
}

func (x *MessageHeader) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *MessageHeader) GetMessageId() []byte {
	if x != nil {
		return x.MessageId
	}
	return nil
}

func (x *MessageHeader) GetThreadId() []byte {
	if x != nil {
		return x.ThreadId
	}
	return nil
}

func (x *MessageHeader) GetSenderAddress() string {
	if x != nil {
		return x.SenderAddress
	}
	return ""
}

func (x *MessageHeader) GetSenderPublicKey() []byte {
	if x != nil {
		return x.SenderPublicKey
	}
	return nil
}

func (x *MessageHeader) GetRecipientAddress() string {
	if x != nil {
		return x.RecipientAddress
	}
	return ""
}

func (x *MessageHeader) GetSentAt() int64 {
	if x != nil {
		return x.SentAt
	}
	return 0
}

func (x *MessageHeader) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *MessageHeader) GetAttachmentCount() uint32 {
	if x != nil {
		return x.AttachmentCount
	}
	return 0
}

func (x *MessageHeader) GetBodySize() uint64 {
	if x != nil {
		return x.BodySize
	}
	return 0
}

func (x *MessageHeader) GetSnippet() string {
	if x != nil {
		return x.Snippet
	}
	return ""
}

func (x *MessageHeader) GetReplyToId() []byte {
	if x != nil {
		return x.ReplyToId
	}
	return nil
}

func (x *MessageHeader) GetBodyHash() []byte {
	if x != nil {
		return x.BodyHash
	}
	return nil
}

func (x *MessageHeader) GetBodyContentAddress() []byte {
	if x != nil {
		return x.BodyContentAddress
	}
	return nil
}

func (x *MessageHeader) GetTo() []string {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *MessageHeader) GetCc() []string {
	if x != nil {
		return x.Cc
	}
	return nil
}

func (x *MessageHeader) GetBcc() []string {
	if x != nil {
		return x.Bcc
	}
	return nil
}

// SignedHeader wraps a MessageHeader with the sender's signature (covers body_hash,
// so verifying the header authenticates the eventual body too).
type SignedHeader struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Header          *MessageHeader         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	SenderSignature []byte                 `protobuf:"bytes,2,opt,name=sender_signature,json=senderSignature,proto3" json:"sender_signature,omitempty"` // 64 bytes Ed25519 over canonical MessageHeader
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SignedHeader) Reset() {
	*x = SignedHeader{}
	mi := &file_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedHeader) ProtoMessage() {}

func (x *SignedHeader) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedHeader.ProtoReflect.Descriptor instead.
func (*SignedHeader) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{5}
}

func (x *SignedHeader) GetHeader() *MessageHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *SignedHeader) GetSenderSignature() []byte {
	if x != nil {
		return x.SenderSignature
	}
	return nil
}

// MessageContent is the large part: body + attachments. Verified against
// MessageHeader.body_hash when fetched.
type MessageContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          *MessageBody           `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	Attachments   []*AttachmentRecord    `protobuf:"bytes,2,rep,name=attachments,proto3" json:"attachments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageContent) Reset() {
	*x = MessageContent{}
	mi := &file_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageContent) ProtoMessage() {}

func (x *MessageContent) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageContent.ProtoReflect.Descriptor instead.
func (*MessageContent) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{6}
}

func (x *MessageContent) GetBody() *MessageBody {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *MessageContent) GetAttachments() []*AttachmentRecord {
	if x != nil {
		return x.Attachments
	}
	return nil
}

// RecipientRecord holds the wrapped CEK for a single recipient device.
// See whitepaper Section 15.3.3.
type RecipientRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      []byte                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`                  // 16 bytes UUID
	RecipientXPub []byte                 `protobuf:"bytes,2,opt,name=recipient_x_pub,json=recipientXPub,proto3" json:"recipient_x_pub,omitempty"` // 32 bytes X25519 public key of recipient
	EphemeralXPub []byte                 `protobuf:"bytes,3,opt,name=ephemeral_x_pub,json=ephemeralXPub,proto3" json:"ephemeral_x_pub,omitempty"` // 32 bytes per-recipient ephemeral X25519 public key
	WrappedCek    []byte                 `protobuf:"bytes,4,opt,name=wrapped_cek,json=wrappedCek,proto3" json:"wrapped_cek,omitempty"`            // AES-256-GCM ciphertext of CEK
	CekNonce      []byte                 `protobuf:"bytes,5,opt,name=cek_nonce,json=cekNonce,proto3" json:"cek_nonce,omitempty"`                  // 12 bytes nonce for CEK wrapping
	CekTag        []byte                 `protobuf:"bytes,6,opt,name=cek_tag,json=cekTag,proto3" json:"cek_tag,omitempty"`                        // 16 bytes GCM auth tag for CEK wrapping
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecipientRecord) Reset() {
	*x = RecipientRecord{}
	mi := &file_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecipientRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecipientRecord) ProtoMessage() {}

func (x *RecipientRecord) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecipientRecord.ProtoReflect.Descriptor instead.
func (*RecipientRecord) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{7}
}

func (x *RecipientRecord) GetDeviceId() []byte {
	if x != nil {
		return x.DeviceId
	}
	return nil
}

func (x *RecipientRecord) GetRecipientXPub() []byte {
	if x != nil {
		return x.RecipientXPub
	}
	return nil
}

func (x *RecipientRecord) GetEphemeralXPub() []byte {
	if x != nil {
		return x.EphemeralXPub
	}
	return nil
}

func (x *RecipientRecord) GetWrappedCek() []byte {
	if x != nil {
		return x.WrappedCek
	}
	return nil
}

func (x *RecipientRecord) GetCekNonce() []byte {
	if x != nil {
		return x.CekNonce
	}
	return nil
}

func (x *RecipientRecord) GetCekTag() []byte {
	if x != nil {
		return x.CekTag
	}
	return nil
}

// EncryptedEnvelope is the outer transport structure for encrypted messages.
// See whitepaper Section 15.3.3.
type EncryptedEnvelope struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Version          uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	MessageId        []byte                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"` // 16 bytes UUID
	Recipients       []*RecipientRecord     `protobuf:"bytes,3,rep,name=recipients,proto3" json:"recipients,omitempty"`
	EncryptedPayload []byte                 `protobuf:"bytes,4,opt,name=encrypted_payload,json=encryptedPayload,proto3" json:"encrypted_payload,omitempty"`    // AES-256-GCM ciphertext of SignedMessage
	PayloadNonce     []byte                 `protobuf:"bytes,5,opt,name=payload_nonce,json=payloadNonce,proto3" json:"payload_nonce,omitempty"`                // 12 bytes nonce for payload encryption
	PayloadTag       []byte                 `protobuf:"bytes,6,opt,name=payload_tag,json=payloadTag,proto3" json:"payload_tag,omitempty"`                      // 16 bytes GCM auth tag for payload
	PayloadSizeClass uint32                 `protobuf:"varint,7,opt,name=payload_size_class,json=payloadSizeClass,proto3" json:"payload_size_class,omitempty"` // padded size bucket
	CreatedAt        int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                        // Unix seconds
	RatchetPubKey    []byte                 `protobuf:"bytes,9,opt,name=ratchet_pub_key,json=ratchetPubKey,proto3" json:"ratchet_pub_key,omitempty"`           // 32 bytes; zero in protocol v1
	// Split header/body format (additive). When encrypted_header is non-empty the
	// envelope carries a separable, independently-fetchable header and body, both
	// sealed with the same per-message CEK, instead of a single encrypted_payload.
	EncryptedHeader []byte `protobuf:"bytes,10,opt,name=encrypted_header,json=encryptedHeader,proto3" json:"encrypted_header,omitempty"`    // AES-256-GCM ciphertext of SignedHeader
	HeaderNonce     []byte `protobuf:"bytes,11,opt,name=header_nonce,json=headerNonce,proto3" json:"header_nonce,omitempty"`                // 12 bytes
	HeaderTag       []byte `protobuf:"bytes,12,opt,name=header_tag,json=headerTag,proto3" json:"header_tag,omitempty"`                      // 16 bytes
	HeaderSizeClass uint32 `protobuf:"varint,13,opt,name=header_size_class,json=headerSizeClass,proto3" json:"header_size_class,omitempty"` // padded size bucket
	EncryptedBody   []byte `protobuf:"bytes,14,opt,name=encrypted_body,json=encryptedBody,proto3" json:"encrypted_body,omitempty"`          // AES-256-GCM ciphertext of MessageContent
	BodyNonce       []byte `protobuf:"bytes,15,opt,name=body_nonce,json=bodyNonce,proto3" json:"body_nonce,omitempty"`                      // 12 bytes
	BodyTag         []byte `protobuf:"bytes,16,opt,name=body_tag,json=bodyTag,proto3" json:"body_tag,omitempty"`                            // 16 bytes
	BodySizeClass   uint32 `protobuf:"varint,17,opt,name=body_size_class,json=bodySizeClass,proto3" json:"body_size_class,omitempty"`       // padded size bucket
	// Cleartext copy of the body's content address (CIDv1 raw/sha2-256) so relays can
	// verify integrity and (later) key storage on it WITHOUT the CEK. The authoritative
	// copy is the signed one inside encrypted_header (MessageHeader.body_content_address);
	// this one is an unauthenticated routing/dedup hint. Empty pre-feature.
	BodyContentAddress []byte `protobuf:"bytes,18,opt,name=body_content_address,json=bodyContentAddress,proto3" json:"body_content_address,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *EncryptedEnvelope) Reset() {
	*x = EncryptedEnvelope{}
	mi := &file_message_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptedEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptedEnvelope) ProtoMessage() {}

func (x *EncryptedEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptedEnvelope.ProtoReflect.Descriptor instead.
func (*EncryptedEnvelope) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{8}
}

func (x *EncryptedEnvelope) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *EncryptedEnvelope) GetMessageId() []byte {
	if x != nil {
		return x.MessageId
	}
	return nil
}

func (x *EncryptedEnvelope) GetRecipients() []*RecipientRecord {
	if x != nil {
		return x.Recipients
	}
	return nil
}

func (x *EncryptedEnvelope) GetEncryptedPayload() []byte {
	if x != nil {
		return x.EncryptedPayload
	}
	return nil
}

func (x *EncryptedEnvelope) GetPayloadNonce() []byte {
	if x != nil {
		return x.PayloadNonce
	}
	return nil
}

func (x *EncryptedEnvelope) GetPayloadTag() []byte {
	if x != nil {
		return x.PayloadTag
	}
	return nil
}

func (x *EncryptedEnvelope) GetPayloadSizeClass() uint32 {
	if x != nil {
		return x.PayloadSizeClass
	}
	return 0
}

func (x *EncryptedEnvelope) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *EncryptedEnvelope) GetRatchetPubKey() []byte {
	if x != nil {
		return x.RatchetPubKey
	}
	return nil
}

func (x *EncryptedEnvelope) GetEncryptedHeader() []byte {
	if x != nil {
		return x.EncryptedHeader
	}
	return nil
}

func (x *EncryptedEnvelope) GetHeaderNonce() []byte {
	if x != nil {
		return x.HeaderNonce
	}
	return nil
}

func (x *EncryptedEnvelope) GetHeaderTag() []byte {
	if x != nil {
		return x.HeaderTag
	}
	return nil
}

func (x *EncryptedEnvelope) GetHeaderSizeClass() uint32 {
	if x != nil {
		return x.HeaderSizeClass
	}
	return 0
}

func (x *EncryptedEnvelope) GetEncryptedBody() []byte {
	if x != nil {
		return x.EncryptedBody
	}
	return nil
}

func (x *EncryptedEnvelope) GetBodyNonce() []byte {
	if x != nil {
		return x.BodyNonce
	}
	return nil
}

func (x *EncryptedEnvelope) GetBodyTag() []byte {
	if x != nil {
		return x.BodyTag
	}
	return nil
}

func (x *EncryptedEnvelope) GetBodySizeClass() uint32 {
	if x != nil {
		return x.BodySizeClass
	}
	return 0
}

func (x *EncryptedEnvelope) GetBodyContentAddress() []byte {
	if x != nil {
		return x.BodyContentAddress
	}
	return nil
}

var File_message_proto protoreflect.FileDescriptor

const file_message_proto_rawDesc = "" +
	"\n" +
	"\rmessage.proto\x12\fdmcn.message\"J\n" +
	"\vMessageBody\x12!\n" +
	"\fcontent_type\x18\x01 \x01(\tR\vcontentType\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\"\xd2\x01\n" +
	"\x10AttachmentRecord\x12#\n" +
	"\rattachment_id\x18\x01 \x01(\fR\fattachmentId\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x04R\tsizeBytes\x12!\n" +
	"\fcontent_hash\x18\x05 \x01(\fR\vcontentHash\x12\x18\n" +
	"\acontent\x18\x06 \x01(\fR\acontent\"\xac\x03\n" +
	"\x10PlaintextMessage\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\fR\tmessageId\x12\x1b\n" +
	"\tthread_id\x18\x03 \x01(\fR\bthreadId\x12%\n" +
	"\x0esender_address\x18\x04 \x01(\tR\rsenderAddress\x12*\n" +
	"\x11sender_public_key\x18\x05 \x01(\fR\x0fsenderPublicKey\x12+\n" +
	"\x11recipient_address\x18\x06 \x01(\tR\x10recipientAddress\x12\x17\n" +
	"\asent_at\x18\a \x01(\x03R\x06sentAt\x12\x18\n" +
	"\asubject\x18\b \x01(\tR\asubject\x12-\n" +
	"\x04body\x18\t \x01(\v2\x19.dmcn.message.MessageBodyR\x04body\x12@\n" +
	"\vattachments\x18\n" +
	" \x03(\v2\x1e.dmcn.message.AttachmentRecordR\vattachments\x12\x1e\n" +
	"\vreply_to_id\x18\v \x01(\fR\treplyToId\"x\n" +
	"\rSignedMessage\x12<\n" +
	"\tplaintext\x18\x01 \x01(\v2\x1e.dmcn.message.PlaintextMessageR\tplaintext\x12)\n" +
	"\x10sender_signature\x18\x02 \x01(\fR\x0fsenderSignature\"\x9b\x04\n" +
	"\rMessageHeader\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\fR\tmessageId\x12\x1b\n" +
	"\tthread_id\x18\x03 \x01(\fR\bthreadId\x12%\n" +
	"\x0esender_address\x18\x04 \x01(\tR\rsenderAddress\x12*\n" +
	"\x11sender_public_key\x18\x05 \x01(\fR\x0fsenderPublicKey\x12+\n" +
	"\x11recipient_address\x18\x06 \x01(\tR\x10recipientAddress\x12\x17\n" +
	"\asent_at\x18\a \x01(\x03R\x06sentAt\x12\x18\n" +
	"\asubject\x18\b \x01(\tR\asubject\x12)\n" +
	"\x10attachment_count\x18\t \x01(\rR\x0fattachmentCount\x12\x1b\n" +
	"\tbody_size\x18\n" +
	" \x01(\x04R\bbodySize\x12\x18\n" +
	"\asnippet\x18\v \x01(\tR\asnippet\x12\x1e\n" +
	"\vreply_to_id\x18\f \x01(\fR\treplyToId\x12\x1b\n" +
	"\tbody_hash\x18\r \x01(\fR\bbodyHash\x120\n" +
	"\x14body_content_address\x18\x0e \x01(\fR\x12bodyContentAddress\x12\x0e\n" +
	"\x02to\x18\x0f \x03(\tR\x02to\x12\x0e\n" +
	"\x02cc\x18\x10 \x03(\tR\x02cc\x12\x10\n" +
	"\x03bcc\x18\x11 \x03(\tR\x03bcc\"n\n" +
	"\fSignedHeader\x123\n" +
	"\x06header\x18\x01 \x01(\v2\x1b.dmcn.message.MessageHeaderR\x06header\x12)\n" +
	"\x10sender_signature\x18\x02 \x01(\fR\x0fsenderSignature\"\x81\x01\n" +
	"\x0eMessageContent\x12-\n" +
	"\x04body\x18\x01 \x01(\v2\x19.dmcn.message.MessageBodyR\x04body\x12@\n" +
	"\vattachments\x18\x02 \x03(\v2\x1e.dmcn.message.AttachmentRecordR\vattachments\"\xd5\x01\n" +
	"\x0fRecipientRecord\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\fR\bdeviceId\x12&\n" +
	"\x0frecipient_x_pub\x18\x02 \x01(\fR\rrecipientXPub\x12&\n" +
	"\x0fephemeral_x_pub\x18\x03 \x01(\fR\rephemeralXPub\x12\x1f\n" +
	"\vwrapped_cek\x18\x04 \x01(\fR\n" +
	"wrappedCek\x12\x1b\n" +
	"\tcek_nonce\x18\x05 \x01(\fR\bcekNonce\x12\x17\n" +
	"\acek_tag\x18\x06 \x01(\fR\x06cekTag\"\xc7\x05\n" +
	"\x11EncryptedEnvelope\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\fR\tmessageId\x12=\n" +
	"\n" +
	"recipients\x18\x03 \x03(\v2\x1d.dmcn.message.RecipientRecordR\n" +
	"recipients\x12+\n" +
	"\x11encrypted_payload\x18\x04 \x01(\fR\x10encryptedPayload\x12#\n" +
	"\rpayload_nonce\x18\x05 \x01(\fR\fpayloadNonce\x12\x1f\n" +
	"\vpayload_tag\x18\x06 \x01(\fR\n" +
	"payloadTag\x12,\n" +
	"\x12payload_size_class\x18\a \x01(\rR\x10payloadSizeClass\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\x12&\n" +
	"\x0fratchet_pub_key\x18\t \x01(\fR\rratchetPubKey\x12)\n" +
	"\x10encrypted_header\x18\n" +
	" \x01(\fR\x0fencryptedHeader\x12!\n" +
	"\fheader_nonce\x18\v \x01(\fR\vheaderNonce\x12\x1d\n" +
	"\n" +
	"header_tag\x18\f \x01(\fR\theaderTag\x12*\n" +
	"\x11header_size_class\x18\r \x01(\rR\x0fheaderSizeClass\x12%\n" +
	"\x0eencrypted_body\x18\x0e \x01(\fR\rencryptedBody\x12\x1d\n" +
	"\n" +
	"body_nonce\x18\x0f \x01(\fR\tbodyNonce\x12\x19\n" +
	"\bbody_tag\x18\x10 \x01(\fR\abodyTag\x12&\n" +
	"\x0fbody_size_class\x18\x11 \x01(\rR\rbodySizeClass\x120\n" +
	"\x14body_content_address\x18\x12 \x01(\fR\x12bodyContentAddressB-Z+github.com/mertenvg/open-dmcn/dmcnpb;dmcnpbb\x06proto3"

var (
	file_message_proto_rawDescOnce sync.Once
	file_message_proto_rawDescData []byte
)

func file_message_proto_rawDescGZIP() []byte {
	file_message_proto_rawDescOnce.Do(func() {
		file_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)))
	})
	return file_message_proto_rawDescData
}

var file_message_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_message_proto_goTypes = []any{
	(*MessageBody)(nil),       // 0: dmcn.message.MessageBody
	(*AttachmentRecord)(nil),  // 1: dmcn.message.AttachmentRecord
	(*PlaintextMessage)(nil),  // 2: dmcn.message.PlaintextMessage
	(*SignedMessage)(nil),     // 3: dmcn.message.SignedMessage
	(*MessageHeader)(nil),     // 4: dmcn.message.MessageHeader
	(*SignedHeader)(nil),      // 5: dmcn.message.SignedHeader
	(*MessageContent)(nil),    // 6: dmcn.message.MessageContent
	(*RecipientRecord)(nil),   // 7: dmcn.message.RecipientRecord
	(*EncryptedEnvelope)(nil), // 8: dmcn.message.EncryptedEnvelope
}
var file_message_proto_depIdxs = []int32{
	0, // 0: dmcn.message.PlaintextMessage.body:type_name -> dmcn.message.MessageBody
	1, // 1: dmcn.message.PlaintextMessage.attachments:type_name -> dmcn.message.AttachmentRecord
	2, // 2: dmcn.message.SignedMessage.plaintext:type_name -> dmcn.message.PlaintextMessage
	4, // 3: dmcn.message.SignedHeader.header:type_name -> dmcn.message.MessageHeader
	0, // 4: dmcn.message.MessageContent.body:type_name -> dmcn.message.MessageBody
	1, // 5: dmcn.message.MessageContent.attachments:type_name -> dmcn.message.AttachmentRecord
	7, // 6: dmcn.message.EncryptedEnvelope.recipients:type_name -> dmcn.message.RecipientRecord
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_message_proto_init() }
func file_message_proto_init() {
	if File_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_proto_goTypes,
		DependencyIndexes: file_message_proto_depIdxs,
		MessageInfos:      file_message_proto_msgTypes,
	}.Build()
	File_message_proto = out.File
	file_message_proto_goTypes = nil
	file_message_proto_depIdxs = nil
}
